## This file was generated by SPOCK on Wed Apr 22 2009 at 15:30:57.
#####
# SPACE parameter file for FreePDK45 - FreePDK 45nm
#####################################################################

min_art_degree	3
min_degree	4
min_res	100	# ohm
min_sep_res	10	# ohm
max_par_res	25
min_coup_cap	0.04
lat_cap_window	0.5	# micron
low_sheet_res	1.0	# ohm/square
low_contact_res	0.1e-12	# ohm.square meter

BEGIN cap3d
be_mode	0c	# pwc collocation
be_window	0.1	# micron
max_be_area	0.005	# square micron
omit_diff_cap	on	# default=on
omit_gate_ds_cap	on	# default=off
omit_gate_gnd_cap	on	# default=on
END cap3d

BEGIN sub3d
be_mode	0g	# pwc galerkin
be_window	1	# micron
max_be_area	0.1	# square micron
edge_be_ratio	0.01
edge_be_split	0.2
END sub3d

BEGIN subcap3d
END subcap3d

BEGIN sne
frequency	1e9	# Hz
END sne

BEGIN moments
END moments

BEGIN disp
END disp

BEGIN debug
END debug
