
/*
 * ISC License
 *
 * Copyright (C) 1997-2013 by
 *	Arjan van Genderen
 *	Simon de Graaf
 *	Nick van der Meijs
 * Delft University of Technology
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

#define PALLOC(ptr, nel, type) { \
if(nel == 0) ptr = NULL; \
else \
if(!(ptr = (type *)calloc((size_t)(nel), sizeof(type)))) cannot_die(1,0); }

#define REPALLOC(ptr, nel, type) { \
if(nel == 0) ptr = NULL; \
else if(!ptr) { \
if(!(ptr = (type *)calloc((size_t)(nel), sizeof(type)))) cannot_die(1,0); } \
else \
if(!(ptr = (type *)realloc((char *)ptr, (size_t)(nel) * sizeof(type)))) cannot_die(1,0); }

#define Free(ptr) free((char *)ptr)

#define OPENR(fp,fn,m) { if(!(fp = fopen(fn,"r")) && m) cannot_die(2,fn); }
#define OPENW(fp,fn)   { if(!(fp = fopen(fn,"w"))) cannot_die(3,fn); }
#define CLOSE(fp) fclose(fp)

/* terminal (port) types: */
#define INPUT   1
#define INREAD  2
#define INOUT   3
#define OUTPUT  4
#define OUTPUT3 5
#define GLOBAL  6

#define RANGE_NUMBER 6

#define AE 0
#define PE 1
#define WB 2
#define WI 3
#define LE 4
#define VL 5

#define MAX_IN_TAB 50

#define P_E fprintf(stderr,

#define DSCAP_PREFIX '$'        /* prefix used for d/s caps generated by tecc */
#define DSCAP_SUFFIX "$ds"      /* suffix used for d/s caps generated by tecc */
