/*
 * ISC License
 *
 * Copyright (C) 1995-2018 by
 *	Xianfeng Ni
 *	Ulrich Geigenmuller
 *	Simon de Graaf
 * Delft University of Technology
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

/* In the following enumeration of id-numbers for
 * actions, options and so forth, the order is
 * i m p o r t a n t,  because sometimes loop likes
 * "for (i=EXTRACTION_OPTION; i<=END_EXTRACTION_OPTION; i++) ..."
 * are used.  So do not change the order unless you
 * know exactly what you are doing!
 */

#ifndef _option_h
#define _option_h
#include "src/helios/xmrealist.h"

enum {
    NO_OPERATION,

/* The following entries are actions */

    INIT_VALUES,
    READ_F_DEF,
    READ_U_DEF,
    ACC_VALUES,
    GET_VALUES,
    GET_C_DEF,
    SET_VALUES,
    SET3D_VALUES,
    SET_G_DEF,
    SET_F_DEF,
    SET_U_DEF,
    WRITE_HELIOS,
    WRITE_PARAMS,

/* The following entries are used by INIT, READ and WRITE actions */

FIRST_PARAMETER,

    GENERAL,

    EXTRACTION_OPTION,
	EXTRACTION_MODE,
	EXTRACTION_SETTINGS,
	CAPACITANCE_EXTRACTION,
	TYPE_OF_CAPACITANCE,
	RESISTANCE_EXTRACTION,
	SELECTIVE_RESISTANCE,
	SUBSTRATE_RESISTANCE,
	SUBSTRATE_CAPACITANCE,
	FREQ_DEP_REDUCTION,
	MAX_FREQUENCY,
	APPLY_CIRC_RED_HEUR,
    END_EXTRACTION_OPTION,

    CAPACITANCE_FAST,
	LATERAL_CAP_WINDOW,
	LATERAL_COMPENSATE,
	JUNCTION_CAP_TYPE,
	CAP_GND_NODE_NAME,
	CAP_SUB_NODE_NAME,
    END_CAPACITANCE_FAST,

    CAPACITANCE_ACCURATE,
	CAP3D_HIER_EXTRACT,
	CAP3D_OMIT_GATE,
	CAP3D_WINDOW,
	CAP3D_REQ_PREC_INF_MAT,
	CAP3D_MAX_GREEN_TERMS,
	CAP3D_MAX_BE_AREA,
	CAP3D_MAX_COARSE_BE_AREA,
	CAP3D_BE_METHOD,
	CAP3D_BE_SHAPE,
	CAP3D_STEP_SLOPE,
	CAP3D_BE_RATIO,
	CAP3D_BE_SPLIT,
	CAP3D_BE_LW,
	CAP3D_MP_MINDIST,
	CAP3D_HIGHEST_MP,
	CAP3D_JUNCTION_CAP_TYPE,
	CAP3D_GND_NODE_NAME,
	CAP3D_SUB_NODE_NAME,
    END_CAPACITANCE_ACCURATE,

    RESISTANCE_EXTRACT,
	MIN_SHEET_RESISTANCE,
	MAX_DELAYED,
	MAX_MESH_ANGLE,
    END_RESISTANCE_EXTRACT,

    SUBRES_ACCRT_FINE,
	SUB3D_WINDOW,
	SUB3D_REQ_PREC_INF_MAT,
	SUB3D_MAX_GREEN_TERMS,
	SUB3D_MAX_BE_AREA,
	SUB3D_SAWDIST,
	SUB3D_EDGEDIST,
	SUB3D_BE_METHOD,
	SUB3D_BE_SHAPE,
	SUB3D_BE_RATIO,
	SUB3D_BE_SPLIT,
	SUB3D_BE_LW,
	SUB3D_MP_MINDIST,
	SUB3D_HIGHEST_MP,
    END_SUBRES_ACCRT_FINE,

    SUBCAP_FAST_FINE,
	SUB_RC_CONSTANT,
    END_SUBCAP_FAST_FINE,

    SUBCAP_ACCRT_FINE,
	SUBCAP3D_WINDOW,
	SUBCAP3D_REQ_PREC_INF_MAT,
	SUBCAP3D_MAX_GREEN_TERMS,
	SUBCAP3D_MAX_BE_AREA,
	SUBCAP3D_SAWDIST,
	SUBCAP3D_EDGEDIST,
	SUBCAP3D_BE_METHOD,
	SUBCAP3D_BE_SHAPE,
	SUBCAP3D_BE_RATIO,
	SUBCAP3D_BE_SPLIT,
	SUBCAP3D_BE_LW,
	SUBCAP3D_MP_MINDIST,
	SUBCAP3D_HIGHEST_MP,
    END_SUBCAP_ACCRT_FINE,

    CIRCUIT_REDUCTION,
	MIN_ART_DEGREE,
	MIN_DEGREE,
	MIN_RES,
	MIN_SEP_RES,
	MAX_PAR_RES,
	NO_NEG_RES,
	NO_NEG_CAP,
	MIN_COUP_CAP,
	MIN_GROUND_CAP,
	FRAG_COUP_CAP,
	MIN_COUP_AREA,
	MIN_GROUND_AREA,
	FRAG_COUP_AREA,
	EQUI_LINE_RATIO,
    END_CIRCUIT_REDUCTION,

    XSPACE,
	XSPACE_REST,

    MISCELLANEOUS_FINE,
	BACK_ANNOTATION,
	BACK_ANNOTATION_PARAMS,
	ELEM_DEF_FILE,
	AUTO_RUN_PREPRO,
	LATERAL_BASE_WIDTH,
    /* it is important that EXTERNAL_PARAMETER_FRONT, EXTERNAL_PARAMETER_END,
     * are the last (non-dummy)  items before LAST_EXTRACTION_PARAMETER,
     * since they control an inclusion of external parameter files that should
     * happen   a f t e r   the automatically generated parameter file is ready.
     */
	EXTERNAL_PARAMETER_FRONT,
	EXTERNAL_PARAMETER_END,
    END_MISCELLANEOUS_FINE,

    LAST_EXTRACTION_PARAMETER,

    RETRIEVE_OPTION,
	RETRIEVE_FORMAT,
	RETRIEVE_TO_FILE,
	RETRIEVE_HIERARCHY,
    END_RETRIEVE_OPTION,

	SPICE_ADVANCED_OPTION,
	SLS_ADVANCED_OPTION,
	EDIF_ADVANCED_OPTION,
	NLE_ADVANCED_OPTION,
	VHDL_ADVANCED_OPTION,

    LAST_RETRIEVAL_PARAMETER,

    LOAD_LAYOUT_OPTION,

    HIGHLAY,

    MATCH,

    IMPORT_OPTION,
	DATABASE_FOR_IMPORT,
	SELECT_LOCAL_NAME,
    END_IMPORT_OPTION,

    DEVICE_MODELS,

LAST_PARAMETER,

/* The following entries are only used to startup a command operation
   and are not used by INIT, READ, WRITE or SET/GET actions */

    ABOUT_WINDOW,
    CAPACITANCE_DETAILS,
    COMMAND_WINDOW,
    DELETE_CELL,
    HELP,
    JOB_CONTROL,
    MANAGE_STATUS,
    MANUAL_PAGE,
    NEW_DATABASE,
    NEW_TECHNOLOGY,
    QUICK_REFERENCE,
    SUBSTRATE_DETAILS,
    SUBSTRATECAP_DETAILS,
    USED_FILES,

END_OF_TABLE
};

#endif
