/*
 * ISC License
 *
 * Copyright (C) 1995-2018 by
 *	Xianfeng Ni
 *	Ulrich Geigenmuller
 *	Simon de Graaf
 * Delft University of Technology
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

/*
** Generated by X-Designer Educational version
** This code may not be used in any program
** offered for resale or commercial use.
*/
/*
**LIBS: -lXm -lXt -lX11
*/

#include <X11/Xatom.h>
#include <X11/Intrinsic.h>
#include <X11/Shell.h>

#include <Xm/Xm.h>
#include <X11/StringDefs.h>
#include <Xm/CascadeB.h>
#include <Xm/DialogS.h>
#include <Xm/FileSB.h>
#include <Xm/Form.h>
#include <Xm/Frame.h>
#include <Xm/Label.h>
#include <Xm/List.h>
#include <Xm/MessageB.h>
#include <Xm/PushB.h>
#include <Xm/RowColumn.h>
#include <Xm/ScrollBar.h>
#include <Xm/SelectioB.h>
#include <Xm/Separator.h>
#include <Xm/Text.h>
#include <Xm/TextF.h>
#include <Xm/ToggleB.h>
#include <Xm/CascadeBG.h>
#include <Xm/LabelG.h>
#include <Xm/PushBG.h>
#include <Xm/SeparatoG.h>
#include <Xm/ToggleBG.h>

#undef atexit /* Motif header files make this malicious definition */

#include <locale.h>
#include <stdio.h>
#include <stdlib.h>

#include "src/helios/option.h"

extern void DisplayDescription (Widget, XtPointer, XtPointer );

XtAppContext app_context;
Display *display;       /*  Display             */

/* <<<<<  above this line generated by X-Designer */

#include <string.h>
#include <ctype.h>
#include <unistd.h>
#include <sys/stat.h>

#include "src/libddm/dmincl.h"

#include "src/space/auxil/auxil.h"
#include "src/helios/realist.h"

/* #define DEBUG */

#define  DEFAULT_XNLSPATH    "/usr/lib/X11/nls"
#define  DEFAULT_XKEYSYMDB   "/usr/lib/X11/XKeysymDB"
#define  SOLARIS_XKEYSYMDB   "/usr/openwin/lib/X11/XKeysymDB"

/* Note: the version of helios is also specified in xmrealist.xd
   and xmrealist.c */
#define  HELIOS_TOOLNAME  "helios"
char *toolDate    = (char*)"30 June 2017";
char *toolVersion = (char*)"2.1.6";

extern char **environ;

extern void PopupMessageBox (char *message);
extern void ChangeToOtherDatabase ();
extern void AdmVariable (int, int, FILE *);
extern void IndicateRun (int);
extern void add_to_proj_list (char *, char *);

void RealistInit ();
void ReadProcessList ();
void SetMenuSensitive (Boolean status);
void CheckICDPATH ();
void CheckX11Paths ();
void setResources (char *);

DM_PROJECT *dmproject;		/* dmproject key for Opened Database */
FILE *MessageFilePointer;
char *UsersHomeDirectory;
char *OriginalPath;		/* Original Path where you run the program */
char *ProgramPath;		/* Path where the program resides */
char *MessageDescriptionFile;	/* Message Description File */
char *OpenedDatabase;		/* Current Opened Database */
char *PrevisDatabase;		/* Previous Opened Database */

int InitialSetValues = 1;
int NumberOfProcesses;
Process *ProcessItems;
char CmdLine[512];
/*char globalTextBuffer[BUFSIZ];  */   /* BUFSIZ defined in stdio.h */
char globalTextBuffer[2000];

XFontStruct *font1;
XFontStruct *font2;

/* below this line generated by X-Designer >>>> */

int main (int argc, char **argv)
{
/* <<<<<  above this line generated by X-Designer */

    char *argv0 = (char*)"helios";

    if (argc > 1 && !strcmp (argv[1], "-v")) {
        fprintf (stderr, "%s version %s, %s\n", argv0, toolVersion, toolDate);
    }
    if (argc > 1 && *argv[argc-1] != '-') OpenedDatabase = argv[argc-1];

    dmInit (argv0);
    CheckICDPATH ();

    CheckX11Paths ();

/* below this line generated by X-Designer >>>> */

	XtSetLanguageProc ( (XtAppContext) NULL, (XtLanguageProc) NULL, (XtPointer) NULL );
	XtToolkitInitialize ();
	app_context = XtCreateApplicationContext ();
	display = XtOpenDisplay (app_context, NULL, argv0, argv0, NULL, 0, &argc, argv);
	if (!display)
	{
	    printf("%s: can't open display, exiting...\n", argv0);
	    exit (-1);
	}
	// XtOpenDisplay sets locale!
	// Following call resets the locale for reading floating point numbers.
	// This fix the problem, when an user sets the LANG to "dutch", then
	// helios can't read lambda values from a ".dmrc" file.
	setlocale (LC_NUMERIC, "C");

        // Load resource database from a file and set it directly.
	setResources (argv0);

	Shell = new Shell_c;
	Shell->create ( display, argv0, argc, argv, argv0 );
	ManPageWin = new ManPageWin_c;
	ManPageWin->create ( Shell->xd_rootwidget(), (char*)"ManPageWin" );
	ImportWin = new ImportWin_c;
	ImportWin->create ( Shell->xd_rootwidget(), (char*)"ImportWin" );
	UsedFilesWin = new UsedFilesWin_c;
	UsedFilesWin->create ( Shell->xd_rootwidget(), (char*)"UsedFilesWin" );
	QuickRefWin = new QuickRefWin_c;
	QuickRefWin->create ( Shell->xd_rootwidget(), (char*)"QuickRefWin" );
	CmdLineWin = new CmdLineWin_c;
	CmdLineWin->create ( Shell->xd_rootwidget(), (char*)"CmdLineWin" );
	ConfirmWin = new ConfirmWin_c;
	ConfirmWin->create ( Shell->xd_rootwidget(), (char*)"ConfirmWin" );
	DeleteWin = new DeleteWin_c;
	DeleteWin->create ( Shell->xd_rootwidget(), (char*)"DeleteWin" );
	DeviceModelWin = new DeviceModelWin_c;
	DeviceModelWin->create ( Shell->xd_rootwidget(), (char*)"DeviceModelWin" );
	JobControlWin = new JobControlWin_c;
	JobControlWin->create ( Shell->xd_rootwidget(), (char*)"JobControlWin" );
	LoadWin = new LoadWin_c;
	LoadWin->create ( Shell->xd_rootwidget(), (char*)"LoadWin" );
	ExtractWin = new ExtractWin_c;
	ExtractWin->create ( Shell->xd_rootwidget(), (char*)"ExtractWin" );
	XspaceWin = new XspaceWin_c;
	XspaceWin->create ( Shell->xd_rootwidget(), (char*)"XspaceWin" );
	ParSubAccrtWin = new ParSubAccrtWin_c;
	ParSubAccrtWin->create ( Shell->xd_rootwidget(), (char*)"ParSubAccrtWin" );
	ParSubCapFastWin = new ParSubCapFastWin_c;
	ParSubCapFastWin->create (Shell->xd_rootwidget(), (char*)"ParSubCapFastWin");
	ParSubCapAccrtWin = new ParSubCapAccrtWin_c;
	ParSubCapAccrtWin->create (Shell->xd_rootwidget(), (char*)"ParSubCapAccrtWin");
	ParMisWin = new ParMisWin_c;
	ParMisWin->create ( Shell->xd_rootwidget(), (char*)"ParMisWin" );
	ParResWin = new ParResWin_c;
	ParResWin->create ( Shell->xd_rootwidget(), (char*)"ParResWin" );
	ParCapFastWin = new ParCapFastWin_c;
	ParCapFastWin->create ( Shell->xd_rootwidget(), (char*)"ParCapFastWin" );
	ParCapAccurateWin = new ParCapAccurateWin_c;
	ParCapAccurateWin->create ( Shell->xd_rootwidget(), (char*)"ParCapAccurateWin" );
	ParHeuristicsWin = new ParHeuristicsWin_c;
	ParHeuristicsWin->create ( Shell->xd_rootwidget(), (char*)"ParHeuristicsWin" );
	RetrieveWin = new RetrieveWin_c;
	RetrieveWin->create ( Shell->xd_rootwidget(), (char*)"RetrieveWin" );
	RetrieveOptionSPICEWin = new RetrieveOptionSPICEWin_c;
	RetrieveOptionSPICEWin->create ( Shell->xd_rootwidget(), (char*)"RetrieveOptionSPICEWin" );
	RetrieveOptionSLSWin = new RetrieveOptionSLSWin_c;
	RetrieveOptionSLSWin->create ( Shell->xd_rootwidget(), (char*)"RetrieveOptionSLSWin" );
	RetrieveOptionEDIFWin = new RetrieveOptionEDIFWin_c;
	RetrieveOptionEDIFWin->create ( Shell->xd_rootwidget(), (char*)"RetrieveOptionEDIFWin" );
	RetrieveOptionNLEWin = new RetrieveOptionNLEWin_c;
	RetrieveOptionNLEWin->create ( Shell->xd_rootwidget(), (char*)"RetrieveOptionNLEWin" );
	RetrieveOptionVHDLWin = new RetrieveOptionVHDLWin_c;
	RetrieveOptionVHDLWin->create ( Shell->xd_rootwidget(), (char*)"RetrieveOptionVHDLWin" );
	MatchWin = new MatchWin_c;
	MatchWin->create ( Shell->xd_rootwidget(), (char*)"MatchWin" );
	HighlayWin = new HighlayWin_c;
	HighlayWin->create ( Shell->xd_rootwidget(), (char*)"HighlayWin" );
	FileSelectionWin = new FileSelectionWin_c;
	FileSelectionWin->create ( Shell->xd_rootwidget(), (char*)"FileSelectionWin" );
	MacroWin = new MacroWin_c;
	MacroWin->create ( Shell->xd_rootwidget(), (char*)"MacroWin" );
	ExitWin = new ExitWin_c;
	ExitWin->create ( Shell->xd_rootwidget(), (char*)"ExitWin" );
	NewDbWin = new NewDbWin_c;
	NewDbWin->create ( Shell->xd_rootwidget(), (char*)"NewDbWin" );
	SelectionWin = new SelectionWin_c;
	SelectionWin->create ( Shell->xd_rootwidget(), (char*)"SelectionWin" );
	NewTechWin = new NewTechWin_c;
	NewTechWin->create ( Shell->xd_rootwidget(), (char*)"NewTechWin" );
	AboutWin = new AboutWin_c;
	AboutWin->create ( Shell->xd_rootwidget(), (char*)"AboutWin" );
	MessageWin = new MessageWin_c;
	MessageWin->create ( Shell->xd_rootwidget(), (char*)"MessageWin" );
	XtRealizeWidget (Shell->xd_rootwidget());
/* <<<<<  above this line generated by X-Designer */

#if NCF_RELEASE < 400
	XtUnmanageChild (DeviceModelWin->SaveInDbEquiv_Tggl);
#endif

        RealistInit ();

/* below this line generated by X-Designer >>>> */

	XtAppMainLoop (app_context);
	exit (0);
}

char *giveICD (char *filepath)
{
    int len = strlen (icdpath);
    if (strncmp (icdpath, filepath, len)) return filepath;
    return mprintf ("$ICDPATH%s", filepath + len);
}

void RealistInit ()
{
    char **envMarker, *keyword;
    FILE *fp;
    int item;

    /* Get directory from which program was called */
    if (!(OriginalPath = getcwd (NULL, MAXLENGTH_OF_FILENAME+1))) {
        fprintf(stderr, "Could not get current working directory!");
        exit (1);
    }

    XmTextFieldSetString (UsedFilesWin->Icdpath_Txt, icdpath);
    XmTextFieldSetString (UsedFilesWin->StartUpDir_Txt, OriginalPath);

    /* find HOME directory of user from environment variable */
    envMarker = environ;
    while (*envMarker) {
        if (!strncmp (*envMarker, "HOME=", 5)) {
            UsersHomeDirectory = strsave (*envMarker + 5);
            break;
        }
        envMarker++;
    }

    if (OpenedDatabase) add_to_proj_list (OpenedDatabase, NULL);

    /* Read file ~/.helios, to find out which NELSIS database directory was
     * used last time, and which file to use for quick reference guide.
     */
    OpenedDatabase = NULL;
    if ((fp = fopen (mprintf ("%s/.helios", UsersHomeDirectory), "r"))) {
        while (fgets (globalTextBuffer, sizeof (globalTextBuffer), fp)) {
	    keyword = strtok (globalTextBuffer, " \t\n");

	    if (!strcmp (keyword, "OpenedDatabase") ||
		!strcmp (keyword, "PrevisDatabase")) {
		add_to_proj_list (strtok (NULL, " \t\n"), UsersHomeDirectory);
	    }
        }
        fclose (fp);
    }

    MessageDescriptionFile = mprintf ("%s/share/lib/helios/helios.message", icdpath);
    MessageFilePointer = fopen (MessageDescriptionFile, "r");
    if (MessageFilePointer == NULL) {
	PopupMessageBox (mprintf ("%s\n%s\n",
	    "The file containing the quick reference text could not be found.",
	    "The file $ICDPATH/share/lib/helios/helios.message could not be opened."));
	MessageDescriptionFile = (char*)"";
    }

    XmTextFieldSetString (UsedFilesWin->QuickRefFile_Txt, giveICD (MessageDescriptionFile));

    /* This call of DisplayDescription make the routine read in the quick description messages */
    DisplayDescription (NULL, NULL, NULL);

    for (item = FIRST_PARAMETER+1; item < LAST_PARAMETER; item++)
	AdmVariable (item, INIT_VALUES, NULL);

    IndicateRun (0);

    ReadProcessList ();

    ChangeToOtherDatabase ();

    InitialSetValues = 0;
}

#define DBPLFILE "processlist"

void ReadProcessList ()
{
    char LineBuffer[BUFSIZ];
    char pr_name[80];
    int  pr_id;
    char *comment, *s;
    FILE *fp;

    if (!(fp = fopen (mprintf ("%s/share/lib/process/%s", icdpath, DBPLFILE), "r"))) {
	PopupMessageBox (mprintf (
	    "Cannot open the process list file:\n\"%s/share/lib/process/%s\"\n%s\n\"%s\"",
	    icdpath, DBPLFILE,
	    "Check the environment variable ICDPATH, which is currently set to:",
	    icdpath));
	return;
    }

    NumberOfProcesses = 0;
    while (fgets (LineBuffer, BUFSIZ, fp))
	if (isdigit (LineBuffer[0])) ++NumberOfProcesses;
    ProcessItems = NEW (Process, NumberOfProcesses);

    rewind (fp);
    NumberOfProcesses = 0;
    while (fgets (LineBuffer, BUFSIZ, fp)) {
	if (!isdigit (LineBuffer[0])) continue;
	if ((comment = strchr (LineBuffer, '#'))) *comment = '\0';
	sscanf (LineBuffer, "%d %s", &pr_id, pr_name);
	ProcessItems[NumberOfProcesses].index = pr_id;
	ProcessItems[NumberOfProcesses].name = strsave (pr_name);
	if (comment) {
	    *comment = '#';
	    if ((s = strchr (comment, '\n'))) *s = '\0';
	    ProcessItems[NumberOfProcesses].comment = strsave (comment);
	}
	else
	    ProcessItems[NumberOfProcesses].comment = strsave ("");
	NumberOfProcesses++;
    }
    fclose (fp);

    if (!NumberOfProcesses)
	PopupMessageBox ((char*)"No processes found in the process list!");
}

void SetMenuSensitive (Boolean status)
{
    Arg arg;

    XtSetArg (arg, XmNsensitive, status);

    XtSetValues (Shell->ListButton, &arg, 1);
    XtSetValues (Shell->RemoveButton, &arg, 1);
    XtSetValues (Shell->ImportButton, &arg, 1);
    XtSetValues (Shell->DeleteButton, &arg, 1);
    XtSetValues (Shell->CleanButton, &arg, 1);
    XtSetValues (Shell->DeviceModelButton, &arg, 1);
    XtSetValues (Shell->SaveButton, &arg, 1);
    XtSetValues (Shell->LayoutMenu, &arg, 1);
    XtSetValues (Shell->ExtractorMenu, &arg, 1);
    XtSetValues (Shell->CircuitMenu, &arg, 1);
    XtSetValues (Shell->Cell_Frame->ViewType_OptnMn, &arg, 1);
    XtSetValues (UsedFilesWin->Version_Txt, &arg, 1);
    XtSetValues (UsedFilesWin->Technology_Txt, &arg, 1);
    XtSetValues (UsedFilesWin->Lambda_Txt, &arg, 1);
    if (PrevisDatabase) {
	if (status != TRUE)
	    XtSetArg (arg, XmNsensitive, TRUE);
    }
    else {
	if (status != FALSE)
	    XtSetArg (arg, XmNsensitive, FALSE);
    }
    XtSetValues (Shell->PreviousButton, &arg, 1);
}

void ReadUserDefaults (char *fileName)
{
    FILE *fp;
    int item;
    struct stat buf;

    if (stat (fileName, &buf) == 0 && !S_ISDIR (buf.st_mode) &&
		(fp = fopen (fileName, "r"))) {
	for (item = FIRST_PARAMETER+1; item <= LAST_PARAMETER; item++)
	    AdmVariable (item, READ_U_DEF, fp);
	fclose (fp);
	XmTextFieldSetString (UsedFilesWin->UserDfltFile_Txt, giveICD (fileName));
    }
}

void CheckICDPATH ()
{
    char *file = mprintf ("%s/share/lib/process/%s", icdpath, DBPLFILE);
    if (access (file, F_OK) == -1) {
	fprintf (stderr, "\n%s\nthe file \"%s%s\n   \"%s\"\n",
	    "The environment variable ICDPATH is set incorrectly:", DBPLFILE,
	    "\" could not be found at the expected place, viz.", file);
	exit (1);
    }
}

void setResources (char *argv0)
{
    XrmDatabase db, db2;
    XrmValue val1, val2, val3;
    char *s1, *s2, *stype, *f1, *f2;
    char *file, line[512];

    XrmInitialize ();
    db = 0;

    file = mprintf ("%s/share/lib/app-defaults/%s", icdpath, "Helios");
    if (access (file, F_OK) == -1)
	fprintf (stderr, "%s: can't access '%s'\n", argv0, file);
    else
	db = XrmGetFileDatabase (file);

    db2 = XrmGetDatabase (display);
    if (!db2)
	fprintf (stderr, "%s: can't get resource database!\n", argv0);
    else if (db)
	XrmMergeDatabases (db2, &db);
    else
	db = db2;

    f1 = f2 = 0;
    s1 = (char*)"helios*iconPixmap";
    s2 = (char*)"helios*AboutBitmap.labelPixmap";
    if (XrmGetResource (db, s1, "", &stype, &val1) == True) f1 = val1.addr;
    if (XrmGetResource (db, s2, "", &stype, &val2) == True) f2 = val2.addr;

    if (f1 && !strcmp (f1, "AUTOMATIC")) f1 = 0;
    if (f2 && !strcmp (f2, "AUTOMATIC")) f2 = 0;

    if (!f1 || access (f1, F_OK) == -1) {
	file = mprintf ("%s/share/lib/helios/%s", icdpath, "helios.icon");
	if (access (file, F_OK) == -1) {
	    if (f1) file = f1;
	    fprintf (stderr, "%s: can't access '%s'\n", argv0, file);
	}
	else {
	    sprintf (line, "%s: %s", s1, file);
	    XrmPutLineResource (&db, line);
	}
    }

    if (!f2 || access (f2, F_OK) == -1) {
	file = mprintf ("%s/share/lib/helios/%s", icdpath, "sram.xpm");
	if (access (file, F_OK) == -1) {
	    if (f2) file = f2;
	    fprintf (stderr, "%s: can't access '%s'\n", argv0, file);
	}
	else {
	    sprintf (line, "%s: %s", s2, file);
	    XrmPutLineResource (&db, line);
	}
    }

    f1 = (char*)"helios.headfont";
    if (XrmGetResource (db, f1, "", &stype, &val3) == True) {
	s1 = val3.addr;
	font1 = XLoadQueryFont (display, s1);
	if (!font1)
	    fprintf (stderr, "%s: font '%s' not found!\n", argv0, s1);
    }
    else
	fprintf (stderr, "%s: resource '%s' not found!\n", argv0, f1);

    f2 = (char*)"helios*FontList";
    if (XrmGetResource (db, f2, "", &stype, &val3) == True) {
	s1 = val3.addr;
	s2 = line;
	while (*s1 && *s1 != '=' && *s1 != ',') *s2++ = *s1++;
	*s2 = '\0';
	font2 = XLoadQueryFont (display, line);
	if (!font2)
	    fprintf (stderr, "%s: font '%s' not found!\n", argv0, line);
    }
    else
	fprintf (stderr, "%s: resource '%s' not found!\n", argv0, f2);

    XrmSetDatabase (display, db);
}

void CheckX11Paths ()
{
    int err = 0;
    char *pathA;
    char *pathB;

    if (!(pathA = getenv ("XNLSPATH"))) pathA = (char*)DEFAULT_XNLSPATH;

    if (!(pathB = getenv ("XKEYSYMDB"))) {
#ifdef __SUNOS__
        if (access (SOLARIS_XKEYSYMDB, F_OK | R_OK) >= 0) return;
#endif
        pathB = (char*)DEFAULT_XKEYSYMDB;
    }

    if (access (pathB, F_OK | R_OK) < 0) {
        fprintf (stderr, "Cannot open directory '%s', please set the environment variable XKEYSYMDB to the directory containing the key symbol database.\n",
        pathB);
        err++;
    }

#if defined(__SUNOS__) || defined(__HPUX__)
    if (access (pathA, F_OK | R_OK) < 0 && strcmp (pathB, SOLARIS_XKEYSYMDB)) {
        /* only error when openwin is not used */
        fprintf (stderr, "Cannot open directory '%s', please set the environment variable XNLSPATH to the directory with X-Windows native language support stuff.\n",
        pathA);
        err++;
    }
#endif

    /* no exit anymore since otherwise the program will not run
       when it works without the key symbol and nls directory.
    if (err)
        exit (1);
    */
}

#ifdef STATIC
/* libX11.a fix for static linking */
extern "C" void *dlopen (const char *filename, int flag);
void *dlopen (const char *filename, int flag)
{
    return NULL;
}
#endif
