/*
 * ISC License
 *
 * Copyright (C) 1995-2018 by
 *	Xianfeng Ni
 *	Ulrich Geigenmuller
 *	Simon de Graaf
 * Delft University of Technology
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

/*
** Generated by X-Designer Educational version
** This code may not be used in any program
** offered for resale or commercial use.
*/
#ifndef _xmrealist_h
#define _xmrealist_h

#define XD_MOTIF

#include "src/helios/xdclass.h"

class Cell_Frame_c: public xd_XmFrame_c {
public:
	virtual void create (Widget parent, char *widget_name = NULL);
	Widget Cell_Frame;
	Widget ViewType_OptnMn;
	Widget layout_Bttn;
	Widget circuit_Bttn;
	Widget SelectedCell_Txt;
	Widget LayCellsList;
	Widget CirCellsList;
protected:
	Widget SelectedCell_Lbl;
	Widget SelectedCellClear_Bttn;
};

typedef Cell_Frame_c *Cell_Frame_p;

class WorkArea_Frame_c: public xd_XmFrame_c {
public:
	virtual void create (Widget parent, char *widget_name = NULL);
	Widget WorkArea_Frame;
	Widget WorkAreaText;
protected:
	Widget WorkAreaVertScrollBar;
	Widget WorkAreaSave_Bttn;
	Widget WorkAreaClear_Bttn;
};

typedef WorkArea_Frame_c *WorkArea_Frame_p;

class Shell_c: public xd_ApplicationShell_c {
public:
	virtual void create (Display *display, char *app_name, int app_argc, char **app_argv, char *app_class_name)
;
	Shell_c();
	virtual ~Shell_c();
	Widget Shell;
	Widget ShellDialog;
	Widget PreviousButton;
	Widget ListButton;
	Widget CleanButton;
	Widget NewButton;
	Widget RemoveButton;
	Widget ImportButton;
	Widget DeleteButton;
	Widget DeviceModelButton;
	Widget NewTechButton;
	Widget SaveButton;
	Widget LayoutMenu;
	Widget ExtractorMenu;
	Widget CircuitMenu;
	Widget SetUserDflt_Tggl;
	Widget SetFactoryDflt_Tggl;
	Widget SetGeneralDflt_Tggl;
	Widget DontLoadForms_Tggl;
	Widget ChangePrompt_Tggl;
	Widget RunIndicator_Lbl;
	Cell_Frame_p Cell_Frame;
	WorkArea_Frame_p WorkArea_Frame;
protected:
	Widget MenuBar;
	Widget DatabaseMenu;
	Widget OpenButton;
	Widget OpenImpButton;
	Widget SaveAsButton;
	Widget LoadSettings_Bttn;
	Widget ExitButton;
	Widget LoadLayout_Bttn;
	Widget MacroButton;
	Widget DaliButton;
	Widget Extract_Bttn;
	Widget ExtractionOptn_Bttn;
	Widget ExtractDisplay_Bttn;
	Widget RunRetrieve_Bttn;
	Widget RetrieveOptn_Bttn;
	Widget Highlay_Bttn;
	Widget Match_Bttn;
	Widget SimeyeButton;
	Widget OptionsMenu;
	Widget ShowQuickRef_Bttn;
	Widget ShowCmdLine_Bttn;
	Widget HelpMenu;
	Widget AboutButton;
	Widget HelpButton;
	Widget ShowUsedFiles_Bttn;
	Widget ManualPage_Bttn;
};

typedef Shell_c *Shell_p;

class ManPageWin_c: public xd_XmDialog_c {
public:
	virtual void create (Widget parent, char *widget_name)
;
	Widget ManPageWin;
	Widget ManPageDialog;
	Widget ManPagesIndex_Lst;
	Widget ManPage_Txt;
protected:
	Widget CloseManPage_Win;
	Widget ManPageIndex_Lbl;
	Widget ManPagesIndex_ScrlldLst;
	Widget ManPageText_Lbl;
};

typedef ManPageWin_c *ManPageWin_p;

class ImportWin_c: public xd_XmDialog_c {
public:
	virtual void create (Widget parent, char *widget_name)
;
	Widget ImportWin;
	Widget ImportDialog;
	Widget ImportProjectList;
	Widget ImportRemoteDatabaseText;
	Widget ImportCellList;
	Widget ImportAllRootCells_Bttn;
	Widget ImportAllCells_Bttn;
	Widget ImpView_OptnMn;
	Widget ImpViewLayout_Bttn;
	Widget ImpViewCircuit_Bttn;
	Widget ImpCellName_OptnMn;
	Widget ImpCellRemName_Bttn;
	Widget ImpCellPrefixedRemName_Bttn;
	Widget ImpCellNewName_Bttn;
	Widget ImportName_Txt;
protected:
	Widget LibList_Frame;
	Widget ImportAdd_Bttn;
	Widget ImportRm_Bttn;
	Widget SelectLibDbase_Bttn;
	Widget RemoteCell_Frame;
	Widget Import_Bttn;
	Widget ImportUnselect_Bttn;
};

typedef ImportWin_c *ImportWin_p;

class UsedFilesWin_c: public xd_XmDialog_c {
public:
	virtual void create (Widget parent, char *widget_name)
;
	Widget UsedFilesWin;
	Widget UsedFilesDialog;
	Widget PWD_Txt;
	Widget Lambda_Txt;
	Widget Technology_Txt;
	Widget Version_Txt;
	Widget Icdpath_Txt;
	Widget StartUpDir_Txt;
	Widget PrevDir_Txt;
	Widget UserDfltFile_Txt;
	Widget TechDfltFile_Txt;
	Widget QuickRefFile_Txt;
protected:
	Widget CloseUsedFilesWin_Bttn;
	Widget presentValues_Frm;
	Widget PWD_Lbl;
	Widget Lamda_Lbl;
	Widget Technology_Lbl;
	Widget Version_Lbl;
	Widget Paths_Frm;
	Widget Icdpath_Lbl;
	Widget StartUpDir_Lbl;
	Widget PrevDir_Lbl;
	Widget ReadFiles_Frm;
	Widget UserDfltFile_Lbl;
	Widget TechDfltFile_Lbl;
	Widget QuickRefFile_Lbl;
};

typedef UsedFilesWin_c *UsedFilesWin_p;

class QuickRefText_Frame_c: public xd_XmFrame_c {
public:
	virtual void create (Widget parent, char *widget_name = NULL);
	Widget QuickRefText_Frame;
	Widget DescriptionText;
};

typedef QuickRefText_Frame_c *QuickRefText_Frame_p;

class QuickRefWin_c: public xd_XmDialog_c {
public:
	virtual void create (Widget parent, char *widget_name)
;
	QuickRefWin_c();
	virtual ~QuickRefWin_c();
	Widget QuickRefWin;
	Widget QuickRefDialog;
	QuickRefText_Frame_p QuickRefText_Frame;
	Widget DescriptionItem_Txt;
	Widget DescriptionFloatOnTop_Tggl;
protected:
	Widget Description_Frm;
	Widget CloseQuickRef_Bttn;
};

typedef QuickRefWin_c *QuickRefWin_p;


class CmdLineWin_c: public xd_XmDialog_c {
public:
	virtual void create (Widget parent, char *widget_name)
;
	Widget CmdLineWin;
	Widget CmdLineDialog;
	Widget CommandHistory;
	Widget CmdLine_Txt;
	Widget CmdRun_Bttn;
	Widget CmdCancel_Bttn;
	Widget CmdWinClose_Bttn;
protected:
	Widget CmdHist_Lbl;
	Widget CmdLine_Lbl;
};

typedef CmdLineWin_c *CmdLineWin_p;

class ConfirmWin_c: public xd_XmDialog_c {
public:
	virtual void create (Widget parent, char *widget_name)
;
	Widget ConfirmWin;
	Widget ConfirmDialog;
	Widget Confirm_Lbl;
protected:
	Widget ConfirmOK_Bttn;
	Widget ConfirmCancel_Bttn;
};

typedef ConfirmWin_c *ConfirmWin_p;

class Delete_Frame_c: public xd_XmFrame_c {
public:
	virtual void create (Widget parent, char *widget_name = NULL);
	Widget Delete_Frame;
	Widget DeleteCellList;
	Widget DeleteView_OptnMn;
	Widget DeleteLayoutView_Bttn;
	Widget DeleteCircuitView_Bttn;
protected:
	Widget SelectLocalRootCells_Bttn;
	Widget DeleteCellUnselect_Bttn;
};

typedef Delete_Frame_c *Delete_Frame_p;

class DeleteWin_c: public xd_XmDialog_c {
public:
	virtual void create (Widget parent, char *widget_name)
;
	DeleteWin_c();
	virtual ~DeleteWin_c();
	Widget DeleteWin;
	Widget DeleteDialog;
	Widget DeleteSelectedCells_Bttn;
	Widget DeleteLocalCells_Bttn;
	Widget DeleteImportedCells_Bttn;
	Widget DeleteAllCells_Bttn;
	Delete_Frame_p Delete_Frame;
protected:
	Widget CloseDeleteWin_Bttn;
};

typedef DeleteWin_c *DeleteWin_p;

class DeviceModelWin_c: public xd_XmDialog_c {
public:
	virtual void create (Widget parent, char *widget_name)
;
	Widget DeviceModelWin;
	Widget DeviceModelDialog;
	Widget SaveDevModInDb_Bttn;
	Widget DevModFromFile_Tggl;
	Widget DevModFromDbase_Tggl;
	Widget DevModFromFile_Frm;
	Widget DevModFromFile_Bttn;
	Widget DevModFromFile_Txt;
	Widget DevModFromDbase_Frm;
	Widget DevModFromDbase_Bttn;
	Widget DbaseWithDevMod_Txt;
	Widget SelectDevFromDbase_Bttn;
	Widget DevModFromDbase_Txt;
	Widget DeviceName_Txt;
	Widget DevModPrefix_Txt;
	Widget DevModTerminals_Txt;
	Widget DevModInformal_Txt;
	Widget DevModFormal_Txt;
	Widget SaveInFile;
	Widget SaveInDb;
	Widget SaveInDbEquiv_Tggl;
protected:
	Widget DevModSelect_Frame;
	Widget DevModSelect_Rbox;
	Widget DevModEdit_Frame;
	Widget DeviceName_Lbl;
	Widget DevModPrefix_Lbl;
	Widget DevModTerminals_Lbl;
	Widget DevModInformal_Lbl;
	Widget DevModFormal_Lbl;
};

typedef DeviceModelWin_c *DeviceModelWin_p;

class JobControlWin_c: public xd_XmDialog_c {
public:
	virtual void create (Widget parent, char *widget_name)
;
	Widget JobControlWin;
	Widget JobControlDialog;
	Widget Job0_Txt;
	Widget Job1_Txt;
	Widget Job2_Txt;
	Widget Job3_Txt;
	Widget Job4_Txt;
	Widget StopJob0;
	Widget StopJob1;
	Widget StopJob2;
	Widget StopJob3;
	Widget StopJob4;
protected:
	Widget CloseJobCntrl_Bttn;
	Widget JobList;
};

typedef JobControlWin_c *JobControlWin_p;

class LoadWin_c: public xd_XmDialog_c {
public:
	virtual void create (Widget parent, char *widget_name)
;
	Widget LoadWin;
	Widget LoadDialog;
	Widget LoadLayout_OptnMn;
	Widget CIF_Bttn;
	Widget GDSII_Bttn;
	Widget LDM_Bttn;
	Widget LoadFileText;
	Widget CIFSpecials_Frm;
	Widget LoadOptionCIFunitText;
	Widget Test45_Tggl;
	Widget CellOverwrite_Tggl;
	Widget NonGDS_Frm;
	Widget OnlySyntaxCheck_Tggl;
	Widget NoOrigin_Tggl;
	Widget GDSSpecials_Frm;
	Widget MaskList_Tggl;
	Widget CustomGDSIIMaskList_Bttn;
	Widget LoadOptionMaskListText;
	Widget GDSTerminalForText_Tggl;
	Widget GDSTerminalWidth_Txt;
	Widget LoadVerbose_Tggl;
protected:
	Widget LoadCascadeButton;
	Widget ImportLayout_Bttn;
	Widget LoadOption_Frame;
	Widget CIFunit_Lbl;
};

typedef LoadWin_c *LoadWin_p;

class ExtractWin_c: public xd_XmDialog_c {
public:
	virtual void create (Widget parent, char *widget_name)
;
	Widget ExtractWin;
	Widget ExtractDialog;
	Widget AcceptExtract_Bttn;
	Widget ExtractMode_OptnMn;
	Widget ExtractFlat_Bttn;
	Widget ExtractHierIncr_Bttn;
	Widget ExtractHierNonIncr_Bttn;
	Widget ExtrVerbose_Tggl;
	Widget ExtrTop_Tggl;
	Widget CapExtract_OptnMn;
	Widget CapExtractNone_Bttn;
	Widget CapExtractFast_Bttn;
	Widget CapExtractAccrt_Bttn;
	Widget CapType_OptnMn;
	Widget CapSubstrOnly_Bttn;
	Widget CapCouplSubstr_Bttn;
	Widget CapAll_Bttn;
	Widget CapFineControl_Bttn;
	Widget ResExtract_OptnMn;
	Widget ResExtractNone_Bttn;
	Widget ResExtractFast_Bttn;
	Widget ResExtractAccrt_Bttn;
	Widget ResType_OptnMn;
	Widget ResExtrAll_Bttn;
	Widget ResExtrSpeci_Bttn;
	Widget ResExtrButSpeci_Bttn;
	Widget ResFineControl_Bttn;
	Widget SubstrateRes_OptnMn;
	Widget SubstrateNone_Bttn;
	Widget SubstrateFast_Bttn;
	Widget SubstrateAccrt_Bttn;
	Widget SubstrateResFineControl_Bttn;
	Widget SubstrateCap_OptnMn;
	Widget SubstrateCapNone_Bttn;
	Widget SubstrateCapFast_Bttn;
	Widget SubstrateCapAccrt_Bttn;
	Widget SubstrateCapFineControl_Bttn;
	Widget ReducHeur_OptnMn;
	Widget NoApplyHeur_Bttn;
	Widget ApplyHeur_Bttn;
	Widget CircuitFineControlButton;
	Widget FreqDep_Frm;
	Widget FreqDep_OptnMn;
	Widget FreqIndep_Bttn;
	Widget FreqDep_Bttn;
	Widget max_frequency_Lbl;
	Widget max_frequency_text;
	Widget GHz_Lbl;
protected:
	Widget AcceptExtractOption_Bttn;
	Widget ExtractionSetDflt_Bttn;
	Widget ExtrCancel_Bttn;
	Widget ExtrModePrmtrs;
	Widget ExtractMode_Lbl;
	Widget CapExtractBasicPrmtrs;
	Widget CapExtr_Lbl;
	Widget CapExtType_Lbl;
	Widget CapType_Lbl;
	Widget ResExtrPrmtrs;
	Widget InterconRes_Lbl;
	Widget IntConResType_Lbl;
	Widget SubstrResPrmtrs;
	Widget SubstrRes_Lbl;
	Widget SubstrCapPrmtrs;
	Widget SubstrCap_Lbl;
	Widget CircuitRedPrmtrs;
	Widget CircuitRed_Lbl;
	Widget MoreOptions_Bttn;
};

typedef ExtractWin_c *ExtractWin_p;

class XspaceWin_c: public xd_XmDialog_c {
public:
	virtual void create (Widget parent, char *widget_name)
;
	Widget XspaceWin;
	Widget XspaceDialog;
	Widget XAcceptExtract_Bttn;
	Widget XUse_Tggl;
	Widget XSpace_Frm;
	Widget XGeneral_Frm;
	Widget XSynch_Tggl;
	Widget XShowMenu_Tggl;
	Widget XwindowWidth_Txt;
	Widget XwindowHeight_Txt;
	Widget XTiles_Frm;
	Widget XTileBound_Tggl;
	Widget XTiles_Tggl;
	Widget XInputEdge_Tggl;
	Widget XMesh_Frm;
	Widget X3d_Tggl;
	Widget XGreen_Tggl;
	Widget XBeMesh_Tggl;
	Widget XBeMeshOnly_Tggl;
	Widget XInterRes_Frm;
	Widget XEquiPot_Tggl;
	Widget XOutputRes_Tggl;
	Widget XResistor_Tggl;
	Widget XFeMesh_Tggl;
	Widget XSubRes_Frm;
	Widget XSubTerm_Tggl;
	Widget XDelaunay_Tggl;
	Widget XSubRes_Tggl;
protected:
	Widget XAccept_Bttn;
	Widget XSpaceDflt_Bttn;
	Widget XSpaceCancel_Bttn;
	Widget XGeneral_Lbl;
	Widget XwindowWidth_Lbl;
	Widget XwindowHeight_Lbl;
	Widget XMesh_Lbl;
	Widget XResistance_Lbl;
};

typedef XspaceWin_c *XspaceWin_p;

class ParSubAccrtWin_c: public xd_XmDialog_c {
public:
	virtual void create (Widget parent, char *widget_name)
;
	Widget ParSubAccrtWin;
	Widget ParSubAccrtDialog;
	Widget SubAcc_Frm;
	Widget Sub3dReqPrec_Txt;
	Widget Sub3dWindow_Txt;
	Widget Sub3dMaxGreenTerms_Txt;
	Widget SawDist_Txt;
	Widget EdgeDist_Txt;
	Widget Sub3dBeMode_OptnMn;
	Widget Sub3d0c_Bttn;
	Widget Sub3d0g_Bttn;
	Widget Sub3d1g_Bttn;
	Widget Sub3dBeShape_OptnMn;
	Widget Sub3dBeShapeNoPref_Bttn;
	Widget Sub3dBeShape3_Bttn;
	Widget Sub3dBeShape4_Bttn;
	Widget Sub3dBeRatio_Txt;
	Widget Sub3dBeSplit_Txt;
	Widget Sub3dBeLw_Txt;
	Widget Sub3dBeMaxArea_Txt;
	Widget Sub3dMpMindist_Txt;
	Widget Sub3dMpOrder_OptnMn;
	Widget Sub3dMnpl_Bttn;
	Widget Sub3dDpl_Bttn;
	Widget Sub3dQdrpl_Bttn;
	Widget Sub3dOctpl_Bttn;
protected:
	Widget ParSubAccrt_OK;
	Widget ParSubAccrtDflt;
	Widget ParSubAccrt_Cancel;
	Widget SubResInfMat;
	Widget Sub3dInfMatHead;
	Widget Sub3dReqPrec_Lbl;
	Widget Sub3dWindow_Lbl;
	Widget Sub3dWindow_Unit;
	Widget Sub3dMaxGrT_Lbl;
	Widget EdgeEffectsPrmtr;
	Widget EdgeEffects_Lbl;
	Widget SawDist_Lbl;
	Widget SawDistUnit;
	Widget EdgeDist_Lbl;
	Widget EdgeDistUnit;
	Widget Sub3dBePrmtrs;
	Widget Sub3dBe_Lbl;
	Widget Sub3dBeMode_Lbl;
	Widget Sub3dBeShape_Lbl;
	Widget Sub3dBeRatio_Lbl;
	Widget Sub3dBeSplit_Lbl;
	Widget Sub3dBeLw_Lbl;
	Widget Sub3dBeMaxArea_Lbl;
	Widget Sub3dBeMaxArea_Unit;
	Widget Sub3dMpPrmtrs;
	Widget Sub3dMpPrmtrs_Lbl;
	Widget Sub3dMpMindist_Lbl;
};

typedef ParSubAccrtWin_c *ParSubAccrtWin_p;

class ParSubCapFastWin_c: public xd_XmDialog_c {
public:
	virtual void create (Widget parent, char *widget_name);
	Widget ParSubCapFastWin;
	Widget ParSubCapFastDialog;
	Widget ParSubCapFastFrm;
	Widget sub_rc_const_text;
};

typedef ParSubCapFastWin_c *ParSubCapFastWin_p;

class ParSubCapAccrtWin_c: public xd_XmDialog_c {
public:
	virtual void create (Widget parent, char *widget_name)
;
	Widget ParSubAccrtWin;
	Widget ParSubAccrtDialog;
	Widget SubAcc_Frm;
	Widget Sub3dReqPrec_Txt;
	Widget Sub3dWindow_Txt;
	Widget Sub3dMaxGreenTerms_Txt;
	Widget SawDist_Txt;
	Widget EdgeDist_Txt;
	Widget Sub3dBeMode_OptnMn;
	Widget Sub3d0c_Bttn;
	Widget Sub3d0g_Bttn;
	Widget Sub3d1g_Bttn;
	Widget Sub3dBeShape_OptnMn;
	Widget Sub3dBeShapeNoPref_Bttn;
	Widget Sub3dBeShape3_Bttn;
	Widget Sub3dBeShape4_Bttn;
	Widget Sub3dBeRatio_Txt;
	Widget Sub3dBeSplit_Txt;
	Widget Sub3dBeLw_Txt;
	Widget Sub3dBeMaxArea_Txt;
	Widget Sub3dMpMindist_Txt;
	Widget Sub3dMpOrder_OptnMn;
	Widget Sub3dMnpl_Bttn;
	Widget Sub3dDpl_Bttn;
	Widget Sub3dQdrpl_Bttn;
	Widget Sub3dOctpl_Bttn;
protected:
	Widget ParSubAccrt_OK;
	Widget ParSubAccrtDflt;
	Widget ParSubAccrt_Cancel;
	Widget SubResInfMat;
	Widget Sub3dInfMatHead;
	Widget Sub3dReqPrec_Lbl;
	Widget Sub3dWindow_Lbl;
	Widget Sub3dWindow_Unit;
	Widget Sub3dMaxGrT_Lbl;
	Widget EdgeEffectsPrmtr;
	Widget EdgeEffects_Lbl;
	Widget SawDist_Lbl;
	Widget SawDistUnit;
	Widget EdgeDist_Lbl;
	Widget EdgeDistUnit;
	Widget Sub3dBePrmtrs;
	Widget Sub3dBe_Lbl;
	Widget Sub3dBeMode_Lbl;
	Widget Sub3dBeShape_Lbl;
	Widget Sub3dBeRatio_Lbl;
	Widget Sub3dBeSplit_Lbl;
	Widget Sub3dBeLw_Lbl;
	Widget Sub3dBeMaxArea_Lbl;
	Widget Sub3dBeMaxArea_Unit;
	Widget Sub3dMpPrmtrs;
	Widget Sub3dMpPrmtrs_Lbl;
	Widget Sub3dMpMindist_Lbl;
};

typedef ParSubCapAccrtWin_c *ParSubCapAccrtWin_p;

class ParMisWin_c: public xd_XmDialog_c {
public:
	virtual void create (Widget parent, char *widget_name)
;
	Widget ParMisWin;
	Widget ParMisDialog;
	Widget AutoRunPreprocessorsButton;
	Widget BackAnn_OptnMn;
	Widget BackAnnNone_Bttn;
	Widget BackAnnSome_Bttn;
	Widget BackAnnFull_Bttn;
	Widget HierNameSep_Txt;
	Widget InstTermSep_Txt;
	Widget NetNodeSep_Txt;
	Widget NoLabels_Tggl;
	Widget HierLabels_Tggl;
	Widget HierTerminals_Tggl;
	Widget LeafTerminals_Tggl;
	Widget CellPosName_Tggl;
	Widget TermIsNetname_Tggl;
	Widget NodePosName_Tggl;
	Widget PosNamePrefix_Txt;
	Widget TruNamePrefix_Txt;
	Widget lat_base_width_text;
	Widget ElemDefCustom_Tggl;
	Widget ElemDefFileSlct_Bttn;
	Widget ElemDefFile_Txt;
	Widget ParaFront_Tggl;
	Widget ParaEnd_Tggl;
	Widget ParaFront_Bttn;
	Widget ParaEnd_Bttn;
	Widget ParaFront_Txt;
	Widget ParaEnd_Txt;
protected:
	Widget accept;
	Widget Defaults;
	Widget Cancel;
	Widget MisExtrctPrmtrs;
	Widget BackAnnPrmtrs;
	Widget BackAnn_Lbl;
	Widget HierNameSep_Lbl;
	Widget InstTermSep_Lbl;
	Widget NetNodeSep_Lbl;
	Widget PosNamePrefix_Lbl;
	Widget TruNamePrefix_Lbl;
	Widget ElemDefFile;
	Widget ParaInsert_Lbl;
};

typedef ParMisWin_c *ParMisWin_p;

class ParResWin_c: public xd_XmDialog_c {
public:
	virtual void create (Widget parent, char *widget_name)
;
	Widget ParResWin;
	Widget ParResDialog;
	Widget MinSheetResFrm;
	Widget low_sheet_res_text;
	Widget MaxMeshAngleFrm;
	Widget max_delayed_text;
	Widget max_mesh_angle_text;
protected:
	Widget max_delayed_Lbl;
};

typedef ParResWin_c *ParResWin_p;

class ParCapFastWin_c: public xd_XmDialog_c {
public:
	virtual void create (Widget parent, char *widget_name)
;
	Widget ParCapFastWin;
	Widget ParCapFastDialog;
	Widget CapFast_Frm;
	Widget lat_cap_window_text;
	Widget CompLatPart_Txt;
	Widget JunCaps_OptnMn;
	Widget JC_linear_Bttn;
	Widget JC_non_lin_Bttn;
	Widget JC_area_Bttn;
	Widget JC_area_p_Bttn;
	Widget JC_sepa_Bttn;
	Widget NameGndFast_Txt;
	Widget NameSubFast_Txt;
protected:
	Widget CapFastWinOK;
	Widget CapFastSetDefault;
	Widget CapFastWinCncl;
	Widget LatCapWindowUnit;
	Widget NameGndFast_Lbl;
	Widget NameSubFast_Lbl;
};

typedef ParCapFastWin_c *ParCapFastWin_p;

class ParCapAccurateWin_c: public xd_XmDialog_c {
public:
	virtual void create (Widget parent, char *widget_name)
;
	Widget ParCapAccurateWin;
	Widget ParCapAccurateDialog;
	Widget CapAcc_Frm;
	Widget AllowHierCap3D_Tggl;
	Widget Cap3dOmitGate_Tggl;
	Widget JunCaps3d_OptnMn;
	Widget JC3d_linear_Bttn;
	Widget JC3d_non_lin_Bttn;
	Widget JC3d_area_Bttn;
	Widget JC3d_area_p_Bttn;
	Widget JC3d_sepa_Bttn;
	Widget CapWin3D_Txt;
	Widget ReqPrecInfMat_Txt;
	Widget Cap3dMaxGreenTerms_Txt;
	Widget Cap3dBeMaxArea_Txt;
	Widget Cap3dBeMaxCoArea_Txt;
	Widget Cap3dBeMode_OptnMn;
	Widget ConstCollocation_Bttn;
	Widget ConstGalerkin_Bttn;
	Widget LinGalerkin_Bttn;
	Widget Cap3dBeShape_OptnMn;
	Widget Cap3dBeShapeNoPref_Bttn;
	Widget Cap3dBeShape3_Bttn;
	Widget Cap3dBeShape4_Bttn;
	Widget Cap3dBeRatio_Txt;
	Widget Cap3dBeSplit_Txt;
	Widget Cap3dBeLw_Txt;
	Widget Cap3dStepSlope_Txt;
	Widget Cap3dMpMindist_Txt;
	Widget Cap3dMpOrder_OptnMn;
	Widget Cap3dMnpl_Bttn;
	Widget Cap3dDpl_Bttn;
	Widget Cap3dQdrpl_Bttn;
	Widget Cap3dOctpl_Bttn;
	Widget NameGndAccrt_Txt;
	Widget NameSubAccrt_Txt;
protected:
	Widget CapAccurateWinOK;
	Widget Cap3dSetDefaults;
	Widget CapAccurateWinCancel;
	Widget AllowHierCap3D_Lbl;
	Widget Cap3dOmitGate_Lbl;
	Widget Cap3dInfMat;
	Widget Cap3dInfMat_Lbl;
	Widget Cap3dWindow_Lbl;
	Widget Cap3dWindowUnit;
	Widget Cap3dReqRelPre_Lbl;
	Widget Cap3dMaxGrT_Lbl;
	Widget Cap3dBePrmtrs;
	Widget Cap3dBePrmts_Lbl;
	Widget Cap3dBeMaxArea_Lbl;
	Widget Cap3dBeMaxAreaUnit;
	Widget Cap3dMaxCo_Lbl;
	Widget Cap3dMaxCoUnit;
	Widget Cap3dBeMode_Lbl;
	Widget Cap3dBeShape_Lbl;
	Widget Cap3dBeRatio_Lbl;
	Widget Cap3dBeSplit_Lbl;
	Widget Cap3dBeLw_Lbl;
	Widget Cap3dStepSlope_Lbl;
	Widget Cap3dMultipolePrmtrs;
	Widget Cap3dMP_Lbl;
	Widget Cap3dMpMindist_Lbl;
	Widget Cap3dMpOrder_Lbl;
	Widget NameGndAccrt_Lbl;
	Widget NameSubAccrt_Lbl;
};

typedef ParCapAccurateWin_c *ParCapAccurateWin_p;

class ParHeuristicsWin_c: public xd_XmDialog_c {
public:
	virtual void create (Widget parent, char *widget_name)
;
	Widget ParHeuristicsWin;
	Widget ParHeuristicsDialog;
	Widget HeuristicsValues_Frm;
	Widget min_art_degree_text;
	Widget min_degree_text;
	Widget min_res_text;
	Widget min_sep_res_text;
	Widget max_par_res_text;
	Widget no_neg_res_Tggl;
	Widget MinCoupCap_Txt;
	Widget min_ground_cap_text;
	Widget frag_coup_cap_text;
	Widget no_neg_cap_Tggl;
	Widget MinCoupArea_Txt;
	Widget min_ground_area_text;
	Widget frag_coup_area_text;
	Widget EquiPot_Txt;
protected:
	Widget minArtDgr_Lbl;
	Widget min_art_degree_Lbl2;
	Widget minDegree_Lbl;
	Widget min_degree_Lbl2;
	Widget minRes_Lbl;
	Widget min_res_unit;
	Widget min_sep_res_Lbl;
	Widget min_sep_res_unit;
	Widget max_par_res_Lbl;
	Widget no_neg_res_Lbl;
	Widget MinCoupCap_Lbl;
	Widget MinCoupCap_Lbl2;
	Widget min_ground_cap_Lbl;
	Widget min_ground_cap_unit;
	Widget frag_coup_cap_Lbl;
	Widget MinCoupArea_Lbl;
	Widget MinCoupArea_Lbl2;
	Widget min_ground_area_Lbl;
	Widget min_ground_area_unit;
	Widget frag_coup_area_Lbl;
	Widget equiPot_Lbl;
};

typedef ParHeuristicsWin_c *ParHeuristicsWin_p;

class RetrieveWin_c: public xd_XmDialog_c {
public:
	virtual void create (Widget parent, char *widget_name)
;
	Widget RetrieveWin;
	Widget RetrieveDialog;
	Widget RetrieveFormat_OptnMn;
	Widget RetrieveSPICEButton;
	Widget RetrieveESPICEButton;
	Widget RetrieveHSPICEButton;
	Widget RetrievePSTARButton;
	Widget RetrieveSLSButton;
	Widget RetrieveEDIFButton;
	Widget RetrieveNLEButton;
	Widget RetrieveSPFButton;
	Widget RetrieveSPEFButton;
	Widget RetrieveVHDLButton;
	Widget RetrievalOutputFile_Bttn;
	Widget RetrievalOutputFile_Txt;
	Widget RetrieveToStdout_Bttn;
	Widget RetrieveToFile_Bttn;
	Widget RetrieveToplevel_Bttn;
	Widget RetrieveLocalHier_Bttn;
	Widget RetrieveFullHier_Bttn;
	Widget RetrVerbose_Tggl;
	Widget RetrExclLibs_Tggl;
	Widget RetrExclLibs_Txt;
protected:
	Widget AccAndRetrieve_Bttn;
	Widget AcceptOptn_Bttn;
	Widget RetrieveDflt_Bttn;
	Widget RetrieveFormat_Lbl;
	Widget RetrieveCascadeButton;
	Widget RetrieveOutput_Lbl;
	Widget RetrievalOutputChoice_Rbox;
	Widget RetrieveHier_Lbl;
	Widget RetrievalHierarchy_Rbox;
	Widget RetrieveAdvOpt_Bttn;
};

typedef RetrieveWin_c *RetrieveWin_p;

class RetrieveOptionSPICEWin_c: public xd_XmDialog_c {
public:
	virtual void create (Widget parent, char *widget_name)
;
	Widget RetrieveOptionSPICEWin;
	Widget RetrieveOptionSPICEDialog;
	Widget SPICE_Frm;
	Widget SpiceUseInstNames_Tggl;
	Widget SpiceUseNetNames_Tggl;
	Widget SpiceGndNodeGnd_Tggl;
	Widget SpiceGndNodeVss_Tggl;
	Widget SpiceGndNodeCustom_Tggl;
	Widget SpiceGndNodeCustom_Txt;
	Widget SpiceGndNodeName_Tggl;
	Widget SpiceGndNodeName_Txt;
	Widget SpiceAutoBulk_Tggl;
	Widget SpiceAlwaysPBulk_Tggl;
	Widget SpiceAlwaysNBulk_Tggl;
	Widget SpiceFloatPatch_Tggl;
	Widget SpiceNoUncnnct_Tggl;
	Widget SpiceNoTitle_Tggl;
	Widget SpiceUseCntrlFile_Tggl;
	Widget SpiceCntrlFile_Bttn;
	Widget SpiceCntrlFile_Txt;
	Widget PstarMiscSpecials_Frm;
	Widget UsePstarPn_Tggl;
	Widget UsePstarLl_Tggl;
	Widget SpiceMiscSpecials_Frm;
	Widget SpiceOmitModDef_Tggl;
	Widget SpiceExpandNames_Tggl;
	Widget SpiceDefLabel_Tggl;
	Widget SpiceDefLabel_Txt;
protected:
	Widget SpiceOK_Bttn;
	Widget SpiceSetDflt_Bttn;
	Widget SpiceCncl_Bttn;
	Widget PSTAR_Rbox;
};

typedef RetrieveOptionSPICEWin_c *RetrieveOptionSPICEWin_p;

class RetrieveOptionSLSWin_c: public xd_XmDialog_c {
public:
	virtual void create (Widget parent, char *widget_name)
;
	Widget RetrieveOptionSLSWin;
	Widget RetrieveOptionSLSDialog;
	Widget SLS_Frm;
	Widget SlsExpandNames_Tggl;
	Widget SlsRestDef_Tggl;
	Widget SlsNamesDatabase_Tggl;
	Widget SlsNoUncnnct_Tggl;
	Widget SlsUseCntrlFile_Tggl;
	Widget SlsCntrlFile_Bttn;
	Widget SlsCntrlFile_Txt;
	Widget SlsDefLabel_Tggl;
	Widget SlsDefLabel_Txt;
protected:
	Widget SLS_OK_Bttn;
	Widget SLS_Dflts_Bttn;
	Widget SLS_Cancel_Bttn;
};

typedef RetrieveOptionSLSWin_c *RetrieveOptionSLSWin_p;

class RetrieveOptionEDIFWin_c: public xd_XmDialog_c {
public:
	virtual void create (Widget parent, char *widget_name)
;
	Widget RetrieveOptionEDIFWin;
	Widget RetrieveOptionEDIFDialog;
	Widget EDIF_Frm;
	Widget EdifExpandNames_Tggl;
	Widget EdifShiftIndices_Tggl;
	Widget EdifCadence_Tggl;
	Widget EdifSchematic_Tggl;
	Widget EdifUseCntrlFile_Tggl;
	Widget EdifCntrlFile_Bttn;
	Widget EdifCntrlFile_Txt;
	Widget EdifDefLabel_Tggl;
	Widget EdifDefLabel_Txt;
protected:
	Widget EDIF_OK_Bttn;
	Widget EDIF_Dflts_Bttn;
	Widget EDIF_Cancel_Bttn;
};

typedef RetrieveOptionEDIFWin_c *RetrieveOptionEDIFWin_p;

class RetrieveOptionNLEWin_c: public xd_XmDialog_c {
public:
	virtual void create (Widget parent, char *widget_name)
;
	Widget RetrieveOptionNLEWin;
	Widget RetrieveOptionNLEDialog;
	Widget NLE_Frm;
	Widget NLE_long_Tggl;
	Widget NLE_nbulk_Txt;
	Widget NLE_pbulk_Txt;
	Widget NleUseCntrlFile_Tggl;
	Widget NleCntrlFile_Bttn;
	Widget NleCntrlFile_Txt;
	Widget NleDefLabel_Tggl;
	Widget NleDefLabel_Txt;
protected:
	Widget NLE_OK_Bttn;
	Widget NLE_Dflts_Bttn;
	Widget NLE_Cancel_Bttn;
	Widget NLE_nbulk_Lbl;
	Widget NLE_pbulk_Lbl;
};

typedef RetrieveOptionNLEWin_c *RetrieveOptionNLEWin_p;

class RetrieveOptionVHDLWin_c: public xd_XmDialog_c {
public:
	virtual void create (Widget parent, char *widget_name)
;
	Widget RetrieveOptionVHDLWin;
	Widget RetrieveOptionVHDLDialog;
	Widget VHDL_Frm;
	Widget VHDL_option_r;
	Widget VhdlUseCntrlFile_Tggl;
	Widget VhdlCntrlFile_Bttn;
	Widget VhdlCntrlFile_Txt;
	Widget VhdlDefLabel_Tggl;
	Widget VhdlDefLabel_Txt;
protected:
	Widget VHDL_OK_Bttn;
	Widget VHDL_Dflts_Bttn;
	Widget VHDL_Cancel_Bttn;
};

typedef RetrieveOptionVHDLWin_c *RetrieveOptionVHDLWin_p;

class MatchWin_c: public xd_XmDialog_c {
public:
	virtual void create (Widget parent, char *widget_name)
;
	Widget MatchWin;
	Widget MatchDialog;
	Widget NomNetw_Txt;
	Widget ActNetw_Txt;
	Widget MatchByname_Tggl;
	Widget MatchEdif_Tggl;
	Widget MatchExpand_Tggl;
	Widget MatchFbind_Tggl;
	Widget MatchIgCap_Tggl;
	Widget MatchIgRes_Tggl;
	Widget MatchNomap_Tggl;
	Widget MatchParams_Tggl;
	Widget MatchVerbose_Tggl;
};

typedef MatchWin_c *MatchWin_p;

class HighlayWin_c: public xd_XmDialog_c {
public:
	virtual void create (Widget parent, char *widget_name)
;
	Widget HighlayWin;
	Widget HighlayDialog;
	Widget frame2;
	Widget HighNets_Tggl;
	Widget HighPorts_Tggl;
	Widget HighDevs_Tggl;
	Widget HighNets_Txt;
	Widget HighPorts_Txt;
	Widget HighDevs_Txt;
	Widget radioBox1;
	Widget HighDef_Tggl;
	Widget HighIncon_Tggl;
	Widget HighMatch_Tggl;
	Widget HighVerbose_Tggl;
	Widget Namefile_Bttn;
	Widget Namefile_Txt;
	Widget UseMatch_Bttn;
	Widget UseNamefile_Bttn;
	Widget HighLightMode;
	Widget HLorig_Bttn;
	Widget HLcond_Bttn;
	Widget HLspec_Bttn;
	Widget HLmask_Txt;
protected:
	Widget Highlay;
};

typedef HighlayWin_c *HighlayWin_p;

class FileSelectionWin_c: public xd_XmDialog_c {
public:
	virtual void create (Widget parent, char *widget_name)
;
	Widget FileSelectionWin;
	Widget FileSelectionDialog;
	Widget FileSelectionList;
	Widget FileSelectionText;
protected:
	Widget FileSelectionFilter_Bttn;
	Widget FileSelectionCancel_Bttn;
	Widget FileSelectionHelp_Bttn;
	Widget FileSelectionOK_Bttn;
};

typedef FileSelectionWin_c *FileSelectionWin_p;

class MacroWin_c: public xd_XmDialog_c {
public:
	virtual void create (Widget parent, char *widget_name)
;
	Widget MacroWin;
	Widget MacroDialog;
	Widget Library_Bttn;
	Widget RegularSetList;
	Widget MacroSetList;
	Widget DeviceSetList;
	Widget LibrarySetList;
	Widget LibStatus_Lbl;
	Widget Itype_OptnMn;
	Widget Free_Bttn;
	Widget FMasks_Bttn;
	Widget Strict_Bttn;
	Widget Default_Bttn;
	Widget FMasks_Txt;
	Widget Timestamp_Txt;
	Widget SetRemote_Bttn;
protected:
	Widget MacroStatus_Lbl;
};

typedef MacroWin_c *MacroWin_p;

class ExitWin_c: public xd_XmDialog_c {
public:
	virtual void create (Widget parent, char *widget_name)
;
	Widget ExitWin;
protected:
	Widget ExitDialog;
};

typedef ExitWin_c *ExitWin_p;

class NewDbWin_c: public xd_XmDialog_c {
public:
	virtual void create (Widget parent, char *widget_name)
;
	Widget NewDbWin;
	Widget NewDbDialog;
	Widget ProcessNameText;
	Widget LambdaText;
	Widget DatabaseNameText;
protected:
	Widget Process_Bttn;
	Widget Lambda_Lbl;
	Widget LambdaUnit_Lbl;
	Widget DatabaseName_Bttn;
};

typedef NewDbWin_c *NewDbWin_p;

class SelectionWin_c: public xd_XmDialog_c {
public:
	virtual void create (Widget parent, char *widget_name)
;
	Widget SelectionWin;
	Widget SelectionDialog;
	Widget SelectionList;
};

typedef SelectionWin_c *SelectionWin_p;

class NewTechWin_c: public xd_XmDialog_c {
public:
	virtual void create (Widget parent, char *widget_name)
;
	Widget NewTechWin;
	Widget NewTechDialog;
	Widget NewTechUseProcess;
	Widget NewTechUseMskdata;
	Widget NewTechProcess_Txt;
	Widget NewTechMask_Txt;
	Widget NewTechElemDef_Txt;
	Widget NewTechOptionButton;
protected:
	Widget NewTechProcess_Bttn;
	Widget MaskData_Lbl;
	Widget MaskData_Bttn;
	Widget ElemDefSrc_Lbl;
	Widget NewTechElemDef_Bttn;
	Widget NewTechOK_Bttn;
	Widget NewTechDflts_Bttn;
	Widget NewTechCancel_Bttn;
};

typedef NewTechWin_c *NewTechWin_p;

class AboutWin_c: public xd_XmDialog_c {
public:
	virtual void create (Widget parent, char *widget_name)
;
	Widget AboutWin;
	Widget AboutDialog;
protected:
	Widget AboutDialog_Frm;
	Widget AboutBitmap;
};

typedef AboutWin_c *AboutWin_p;

class MessageWin_c: public xd_XmDialog_c {
public:
	virtual void create (Widget parent, char *widget_name)
;
	Widget MessageWin;
	Widget MessageDialog;
	Widget MessageLabel;
};

typedef MessageWin_c *MessageWin_p;


extern Shell_p Shell;

extern ManPageWin_p ManPageWin;

extern ImportWin_p ImportWin;

extern UsedFilesWin_p UsedFilesWin;

extern QuickRefWin_p QuickRefWin;

extern CmdLineWin_p CmdLineWin;

extern ConfirmWin_p ConfirmWin;

extern DeleteWin_p DeleteWin;

extern DeviceModelWin_p DeviceModelWin;

extern JobControlWin_p JobControlWin;

extern LoadWin_p LoadWin;

extern ExtractWin_p ExtractWin;

extern XspaceWin_p XspaceWin;

extern ParSubAccrtWin_p ParSubAccrtWin;
extern ParSubCapFastWin_p ParSubCapFastWin;
extern ParSubCapAccrtWin_p ParSubCapAccrtWin;

extern ParMisWin_p ParMisWin;

extern ParResWin_p ParResWin;

extern ParCapFastWin_p ParCapFastWin;

extern ParCapAccurateWin_p ParCapAccurateWin;

extern ParHeuristicsWin_p ParHeuristicsWin;

extern RetrieveWin_p RetrieveWin;

extern RetrieveOptionSPICEWin_p RetrieveOptionSPICEWin;

extern RetrieveOptionSLSWin_p RetrieveOptionSLSWin;

extern RetrieveOptionEDIFWin_p RetrieveOptionEDIFWin;

extern RetrieveOptionNLEWin_p RetrieveOptionNLEWin;

extern RetrieveOptionVHDLWin_p RetrieveOptionVHDLWin;

extern MatchWin_p MatchWin;

extern HighlayWin_p HighlayWin;

extern FileSelectionWin_p FileSelectionWin;

extern MacroWin_p MacroWin;

extern ExitWin_p ExitWin;

extern NewDbWin_p NewDbWin;

extern SelectionWin_p SelectionWin;

extern NewTechWin_p NewTechWin;

extern AboutWin_p AboutWin;

extern MessageWin_p MessageWin;

#endif
