/*
 * ISC License
 *
 * Copyright (C) 1988-2018 by
 *	Arjan van Genderen
 *	Simon de Graaf
 *	Nick van der Meijs
 * Delft University of Technology
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

#define HasVBJT(tile)       (tile -> known & 16)
#define HasHighRes(tile)    (tile -> known & 128)

/* The next defines are also used by tecc.
 */
#define SKIP_ELEM    0
#define RESELEM      1
#define TORELEM      2
#define CONTELEM     3
#define SURFCAPELEM  4
#define EDGECAPELEM  5
#define LATCAPELEM   6
#define VDIMELEM     7
#define ESHAPEELEM   8
#define CSHAPEELEM   9

/* bipolar elements */
#define LJUNELEM    10
#define VJUNELEM    11
#define PNCONELEM   12
#define VBJTELEM    13
#define LBJTELEM    14

#define SUBCONTELEM 15
#define NEWMASKELEM 16

/* cap3d element */
#define SURFCAP3DELEM 17
#define EDGECAP3DELEM 18
#define LATCAP3DELEM  19

#define SURFACE    1
#define EDGE       2
#define OTHEREDGE  3

#define HasConduc(tile)  !COLOR_ABSENT (&tile -> color, &filterBitmask)

#define SUBCONT_PREFIX '$'  /* prefix used for substrate contacts (tecc) */
#define DSCAP_PREFIX '$'    /* prefix used for d/s caps generated by tecc */
#define DSCAP_SUFFIX "$ds"  /* suffix used for d/s caps generated by tecc */

