.T= "Back Annotation Application Note"
.ds sU "\s-1SUBSTR\s0
.DS 2
.rs
.sp 1i
.B
.S 15 20
SPACE APPLICATION NOTE
ABOUT
BACK ANNOTATION
.S
.sp 1
.I
S. de Graaf
.sp 1
.R
Circuits and Systems Group
Faculty of Electrical Engineering,
Mathematics and Computer Science
Delft University of Technology
The Netherlands
.DE
.sp 2c
.ce
Report EWI-ENS 03-11
.ce
December 11, 2003
.sp |9i
.DS
.in +5
.S 9
Copyright \s+3\(co\s-3 2003 by the author.

Last revision: December 12, 2003.
.S
.in -5
.DE
.SK
.S=
.H 1 "Introduction"
We had this week, Monday 8 December,
a meeting about this topic with Nick van der Meijs and Kees-Jan van der Kolk.
Some of the \*(sP users (mr.\ Li of Intel) are interested in back annotation
of substrate nodes.
Thus, i shall try to explain something about the back annotation possibilities of the \*(sP system.
.P
Back annotation is used,
to find elements from the cell layout back into the extracted circuit of the cell.
For example the layout positions of transistor devices and terminal nodes.
.P
For extraction with the \*(sP system see the "Space User's Manual"
.[
Gender Meijs Beeftink Elias
.]
and for substrate extraction see the
"Space Substrate Resistance Extraction User's Manual".
.[
Space Substrate Resistance
.]
.P
See also section "Back Annotation", section 2.10 of.
.[
Gender Meijs Beeftink Elias
.]
.P
See also the
.P= space
back annotation options 
.B -x
and
.B -t ,
sections 2.10.7 - 2.10.9 of.
.[
Gender Meijs Beeftink Elias
.]

.H 1 "Back Annotation of Nodes"
For back annotation of nodes,
it is important that the nodes are not eliminated from the extracted network (circuit).
A node is not eliminated, because of one of the following reasons:
.AL
.LI
The node is a terminal or label.
.LI
The node is a device pin.
.LI
The node is a element pin, that must be kept.
.LI
The node is the last node of a node group.
.LI
The node is a substrate terminal.
.LE
.N(
Labels are named (node) positions in the layout (see
.P= dali ).
.N)
.N(
Devices (transistor elements) are never eliminated by
.P= space .
.N)
.N(
Elements can be resistors, capacitors and contacts.
Are specified in the element definition (technology) file,
but can be eliminated.
.N)
.N(
There are only node groups by resistance extraction.
The nodes in the group are connected to each other by resistors.
A node group can be eliminated to one node.
.N)

Nodes can be kept with the
.P= keep_nodes
parameter, see section 2.8.12 of.
.[
Gender Meijs Beeftink Elias
.]
.E(
keep_nodes lcap_cms ecap_cms_cpg.2
.E)
.P
Note that substrate terminals are default not eliminated (except the distributed ones).
.br
But with parameters
.P= elim_sub_term_node
and
.P= elim_sub_node ,
this can be changed.
See also section 6 of.
.[
Space Substrate Resistance
.]
.P
Note that there is also a special
.P= space
option
.B -%f
(fine network) to put off all node elimination.
.P
With
.P= space
parameter
.P= node_pos_name ,
see section 2.10.4 of,
.[
Gender Meijs Beeftink Elias
.]
you can get special net names with the mask and starting (most left/bottom)
net/node position.

.H 1 "Back Annotation of Substrate Nodes"
There are two kinds of substrate nodes:
.AL
.LI
The general node of the substrate, named "\*(sU".
.LI
The substrate terminal nodes.
.LE
.N(
The substrate terminal nodes are connected to "\*(sU" by a substrate resistor.
Substrate terminal nodes exist only, when substrate extraction is done.
.N)
There are two kinds of substrate terminals:
.AL
.LI
Substrate terminals of capacitances and transistors.
These nodes make no real contact with interconnect nodes.
.LI
Substrate terminals of contact elements.
These nodes are connected (via contact resistors) with interconnect nodes.
.LE
.P
See the following figure for an explanation:

.F+
.PSPIC an0311/fig1.ps 4i
.F-

Nodes $N sub 1$, $N sub 2$ and $N sub 3$ are substrate terminals.
Node $N sub 1$ of a substrate contact ($R sub 14$ is the contact resistor).
Node $N sub 3$ is also the bulk pin of transistor $T sub 1$.
Nodes $N sub 4$, $N sub 5$, $N sub s$, $N sub d$ and $N sub g$ are nodes in the interconnect.
Resistors $RS sub 1$, $RS sub 2$, $RS sub 3$, $R sub 12$ and $R sub 23$ are substrate resistors.
There is normally also a substrate resistor between nodes $N sub 1$ and $N sub 3$.
.P
Note that the above substrate nodes are all in different node groups.
However, substrate node $N sub 1$ is in the same node group as node $N sub 4$.
But this node does not get the conductor number (net attribute "cd") of that node group by output.
All substrate terminal nets get "cd=0" by output.
This can be used by other tools, like
.P= xspef
and
.P= xspf .

.H 1 "Examples Listing"
.fS
% space3d -v -E elem.t -P param.p -B sub3term
% xsls sub3term
/* Generated by: xsls 2.34 27-Sep-2000 */
/* Date: 12-Dec-03 8:28:37 GMT */
/* Path: /u/52/52/work/simon/CACD/demo/demo/sub3term/projectname */

network sub3term (terminal c, b, a)
{
    res 1.275388M (c, a);
    res 680.1685k (c, b);
    res 75.8245k (c, SUBSTR);
    res 680.1685k (a, b);
    res 75.8245k (a, SUBSTR);
    res 49.43491k (b, SUBSTR);
}

% space3d -v -E elem.t -P param.p -B -S node_pos_name sub3term
% xsls sub3term
/* Generated by: xsls 2.34 27-Sep-2000 */
/* Date: 12-Dec-03 8:29:55 GMT */
/* Path: /u/52/52/work/simon/CACD/demo/demo/sub3term/projectname */

network sub3term (terminal c, b, a)
{
    net {cmf_40_0, c};
    net {cmf_0_0, a};
    net {cmf_15_30, b};
    res 1.275388M (cmf_40_0, cmf_0_0);
    res 680.1685k (cmf_40_0, cmf_15_30);
    res 75.8245k (cmf_40_0, SUBSTR);
    res 680.1685k (cmf_0_0, cmf_15_30);
    res 75.8245k (cmf_0_0, SUBSTR);
    res 49.43491k (cmf_15_30, SUBSTR);
}

% dbcat -c sub3term
dbcat: -c: list only circuit data
=> circuit/sub3term/mc
cell:"res" inst:"_R1" attr:"v=1.275388e+06" dim:0
cell:"res" inst:"_R2" attr:"v=6.801685e+05" dim:0
cell:"res" inst:"_RS1" attr:"v=7.582450e+04" dim:0
cell:"res" inst:"_R3" attr:"v=6.801685e+05" dim:0
cell:"res" inst:"_RS2" attr:"v=7.582450e+04" dim:0
cell:"res" inst:"_RS3" attr:"v=4.943491e+04" dim:0
=> circuit/sub3term/term
term:"c" attr:"" dim:0
term:"b" attr:"" dim:0
term:"a" attr:"" dim:0
=> circuit/sub3term/net
net:"cmf_40_0" inst:"" attr:"cd=0" subnets:4
    subnet[0]:"c" inst:"" attr:""
    subnet[1]:"p" inst:"_R1" attr:""
    subnet[2]:"p" inst:"_R2" attr:""
    subnet[3]:"p" inst:"_RS1" attr:""
net:"cmf_0_0" inst:"" attr:"cd=0" subnets:4
    subnet[0]:"a" inst:"" attr:""
    subnet[1]:"p" inst:"_R3" attr:""
    subnet[2]:"n" inst:"_R1" attr:""
    subnet[3]:"p" inst:"_RS2" attr:""
net:"cmf_15_30" inst:"" attr:"cd=0" subnets:4
    subnet[0]:"b" inst:"" attr:""
    subnet[1]:"n" inst:"_R3" attr:""
    subnet[2]:"n" inst:"_R2" attr:""
    subnet[3]:"p" inst:"_RS3" attr:""
net:"SUBSTR" inst:"" attr:"cd=0" subnets:3
    subnet[0]:"n" inst:"_RS1" attr:""
    subnet[1]:"n" inst:"_RS2" attr:""
    subnet[2]:"n" inst:"_RS3" attr:""

% space3d -v -E elem.t -P param.p -B -x sub3term
% dbcat -c sub3term
=> circuit/sub3term/mc
cell:"res" inst:"_R1" attr:"v=1.275388e+06" dim:0
cell:"res" inst:"_R2" attr:"v=6.801685e+05" dim:0
cell:"res" inst:"_RS1" attr:"v=7.582450e+04" dim:0
cell:"res" inst:"_R3" attr:"v=6.801685e+05" dim:0
cell:"res" inst:"_RS2" attr:"v=7.582450e+04" dim:0
cell:"res" inst:"_RS3" attr:"v=4.943491e+04" dim:0
=> circuit/sub3term/term
term:"c" attr:"" dim:0
term:"b" attr:"" dim:0
term:"a" attr:"" dim:0
=> circuit/sub3term/net
net:"c" inst:"" attr:"cd=0;x=40;y=5" subnets:3
    subnet[0]:"p" inst:"_R1" attr:""
    subnet[1]:"p" inst:"_R2" attr:""
    subnet[2]:"p" inst:"_RS1" attr:""
net:"a" inst:"" attr:"cd=0;x=0;y=5" subnets:3
    subnet[0]:"p" inst:"_R3" attr:""
    subnet[1]:"n" inst:"_R1" attr:""
    subnet[2]:"p" inst:"_RS2" attr:""
net:"b" inst:"" attr:"cd=0;x=15;y=35" subnets:3
    subnet[0]:"n" inst:"_R3" attr:""
    subnet[1]:"n" inst:"_R2" attr:""
    subnet[2]:"p" inst:"_RS3" attr:""
net:"SUBSTR" inst:"" attr:"cd=0;x=0;y=0" subnets:3
    subnet[0]:"n" inst:"_RS1" attr:""
    subnet[1]:"n" inst:"_RS2" attr:""
    subnet[2]:"n" inst:"_RS3" attr:""
.fE
.in +1c
.ti -1c
.B NOTE :
.br
Because the net contains a terminal, the x,y position of the terminal is used.
The x value is the lower left position of the terminal and the y value is the
center position of the terminal.
By resistance extraction, the x value is also the center position.
.in -1c
.SK
.[
$LIST$
.]
.TC
