.T= "Xspace User's Manual"
.DS 2
.rs
.sp 1i
.B
.S 15 20
XSPACE USER'S MANUAL
.S
.sp 1
.I
A.J. van Genderen,
N.P. van der Meijs
.sp 1
.R
Circuits and Systems Group
Department of Electrical Engineering
Delft University of Technology
The Netherlands
.DE
.sp 2c
.ce
Report ET-NS 96-02
.sp |9i
.DS
.in +5
.S 9
Copyright \s+3\(co\s-3 1996-2005 by the authors.

Last revision: April 25, 2005.
.S
.in -5
.DE
.SK
.S=
.H 1 "Introduction"
.P= Xspace 
is the graphical display tool of the
.P= space3d
program and is an X Window System based application.
.P= Xspace
is used to show the resistance mesh
and the boundary-element mesh that are generated by the
.P= space3d
program,
and to show how the
.P= space3d
program works from an algorithmic point of view.
.P= Xspace 
starts the
.P= space3d
program for each extraction request you give.
The
.P= space3d
program produces a "display.out" file,
which is read by
.P= Xspace
while the
.P= space3d
program is running.
.P
.P= Xspace 
can be invoked as follows:
.DS I
\fBXspace\fR [space3d options] [-X] [X toolkit options] [cell]
.DE
.P
All options of 
.P= space3d
(see the Space User's Manual)
may be used with
.P= Xspace .
Note that, when an option of
.P= Xspace 
is given on the command line,
that corresponds to an option that can be set in the menu of
.P= Xspace ,
this option will be enabled in that menu.
Also when a cell is given as an argument,
that cell will be enabled in the database menu.
.P
The option
.B -X
is used to omit the menu bar of
.P= Xspace.
In that case, a cell name must be given as argument
and all extraction options have to be set at the command line
and/or in the parameter file.
In contrast to when the option
.B -X
is not used,
the program will immediately start the extraction.
.N(
The
.P= space3d
program runs always in \fBflat extraction\fP mode, when started by
.P= Xspace .
With option \fB-v\fP the
.P= space3d
program tells that this "Flat extraction mode"
is forced to "on".
There is one exception,
when parameter "expand_connectivity" is set,
then the program is using the pseudo hierarchical extraction mode.
.N)
Further, the following standard X Windows toolkit options are recognized
by 
.P= Xspace:
.VL 5.8c 0.4c 1
.LI "\fB-bg\fP \fIcolor\fP or"
.LI "\fB-background\fP \fIcolor\fP"
Set the background color to \fIcolor\fP.
.br
Available color names are normally found in the file '/usr/lib/X11/rgb.txt'.
.P
.LI "\fB-bd\fP \fIcolor\fP or"
.LI "\fB-bordercolor\fP \fIcolor\fP"
Set the window border color to \fIcolor\fP.
.P
.LI "\fB-bw\fP \fIwidth\fP or"
.LI "\fB-borderwidth\fP \fIwidth\fP"
Set the window border width to \fIwidth\fP.
.P
.LI "\fB-display\fP \fIhost\fP:\fIdisplay\fP[.\fIscreen\fP]"
Specifies the X server the program should connect to (e.g. victor:0),
this is the display that the program will use for graphical output and input.
If omitted the value of the environment variable DISPLAY is used.
If this environment variable is not set properly either, an error
will be reported by the X Window System.
.P
.LI "\fB-fg\fP \fIcolor\fP or"
.LI "\fB-foreground\fP \fIcolor\fP"
Set the foreground color to \fIcolor\fP.
.P
.LI "\fB-fn\fP \fIfont\fP or"
.LI "\fB-font\fP \fIfont\fP"
The specified font will be used instead of the default
.br
font (which is 'variable', or from \fI.Xdefaults\fP).
.P
.LI "\fB-geometry\fP \fIWxH+X+Y\fP"
Set the window size to \fIW\fP by \fIH\fP and place the window
at location \fIX,Y\fP.
.P
.LI "\fB-iconic\fP"
Start the program as an icon.
.P
.LI "\fB-name\fP \fIname\fP"
Set the application name to \fIname\fP which is used to
.br
retrieve the default setting from the X resource database or the \fI.Xdefaults\fP file.
This facilitates easy switching from one set of X Windows related
preferences to another.
.P
.LI "\fB-rv\fP or"
.LI \fB-reverse\fP
Set 'reverse video' mode.
The results are undefined for color screens.
.P
.LI \fB+rv\fP
Unset 'reverse video' mode (can be used to overrule a 'reverse video' statement
in the user preferences).
.P
.LI "\fB-title\fP \fItitle\fP"
Set the title to \fItitle\fP.
The title is used by some window managers
that provide frames with title bars around windows.
.LI "\fB-xrm\fP '<any X resource>'"
This can be used to overrule any X resource setting
.br
from the command line.
.LE
.SP 2.5
.N(
For
.P= Xspace
examples
see the "Space 3D Capacitance Extraction User's Manual" and
the "Space Substrate Resistance Extraction User's Manual".
.N)
.N(
The X toolkit options are parsed before the
.P= space3d
options.
To be sure, that options like "\fB-ic\fP" and "\fB-rv\fP" are recognized as 
.P= space3d
options,
you can start these options with a '%' sign (like "\fB-%ic\fP").
.N)
.H 1 "Menu Entries"
Unless the option
.B -X
is used,
.P= Xspace
has the following menus:
.H 2 "Extract Menu"
Note that hotkeys are defined for most menu items of this menu.
A defined hotkey is given between parentheses.
.VL 20n 0.4c
.ME "extract  (e)"
Start
.P= space3d
to do the extraction process.
.ME "extract again (a)"
Show display file of an extraction again.
.ME "save pp image"
Toggle, see parameter \fBdisp.save_prepass_image\fP.
.ME "save ep image"
Toggle, see parameter \fBdisp.save_extract_image\fP.
.ME "display clear (c)"
Clear the display (see the save image parameters).
.ME "quit  (q)"
Stop the program and exit.
.ME "pause  (p)"
Start/stop pause showing the extraction output.
.ME "pause afterpp"
Goto pause after each prepass (parameter \fBdisp.pause_after_pp\fP).
.ME "sync"
Toggle X Window System synchronous mode, for easier
.br
debugging and sometimes better pictures.
.ME "run free  (f)"
Don't look for events any more, gives fastest drawing but can
.br
not be interrupted until the extraction is finished.
.ME "single step  (s)"
Go to single step mode.
Use the \fBs\fP-key to do a single step.
Use the \fBd\fP-key to go back to the normal delayed extraction mode
(see also the speed scrollbar).
.ME "robot  (r)"
Start/stop a free hand demo by executing the commands
that are described in the file 'program'.
.ME "reset robot  (R)"
Reset the automatic demo program.
.br
Closes and opens the program file again.
.ME "load params  (l)"
Read the used space parameter file again.
.M)

.H 2 "Database Menu"
A sorted list of cells in the database (radio buttons).
Maximum 34 cells in one menu.
Maximum 102 cells in three separate database menus (Database1, Database2 and Database3).
A specified (dummy) cell argument can position the cells in the menus.
.br
Use parameter "disp.excl_cells \fIcell\fP.." to exclude cells from the menus.
When you want only specific cells in the menus, use "disp.only_cells \fIcell\fP..".
A cell may end with an '*' and the '?' wildcard character may also be used.
.H 2 "Options Menu"
Note that a number of menu items automatically are selected or deselected.
.VL 20n 0.4c
.ME "resistance"
Toggle non-metal interconnect resistance extraction.
Equivalent to the \fB-r\fP option of space (res_values > "low_sheet_res").
.ME "metal resistance"
Toggle non-metal and metal interconnect resistance extraction.
Equivalent to the \fB-%R\fP option (res_values > 0).
.ME "mesh refinement"
Apply a mesh refinement for resistance extraction.
.br
This gives more accurate resistance values (equivalent to \fB-z\fP).
.ME "capacitance"
Toggle ground capacitance extraction.
.br
Equivalent to the \fB-c\fP option of space.
.ME "coupling cap."
Toggle coupling capacitance extraction.
.br
Equivalent to the \fB-C\fP option of space.
.ME "lat. coup. cap."
Toggle lateral coupling capacitance extraction.
.br
Equivalent to the \fB-l\fP option of space.
.ME "3D capacitance"
Toggle 3-dimensional capacitance extraction.
.br
Equivalent to the \fB-3\fP option of space.
.ME "inter. sub. res."
Toggle interpolated substrate resistance extraction.
.br
Equivalent to the \fB-b\fP option of space.
.ME "3D sub. res."
Toggle 3D substrate resistance extraction.
.br
Equivalent to the \fB-B\fP option of space.
.ME "heuristics off"
Toggle network reduction heuristics.
.br
Equivalent to the \fB-n\fP option of space.
.ME "BE mesh only"
Do not compute the capacitances or resistances,
but construct only the boundary-element mesh.
This option is useful for
3D capacitance extraction or 3D substrate resistance extraction.
.br
Equivalent to the \fB-U\fP option of space.
.ME "selective elim."
Extract RC models that are accurate up to a certain frequency.
.br
Equivalent to the \fB-G\fP option of space.
.M)
.SK
.H 2 "Display Menu"
.VL 20n 0.4c
.ME "PairBoundary"
Draw white lines around each tile.
To see also tiles to infinity, give parameter "disp.pair_to_infinity".
To get only lines around tiles with conductivity, use the "disp.pair_conduct_only" parameter.
.ME "DrawTile"
Draw tiles when they are found.
.ME "DrawEdge"
Draw input edges.
.ME "DrawPosition"
Draw scanline position (using pointer).
.ME "DrawResistor"
Toggle resistance drawing.
.br
Only useful with resistance extraction enabled.
.ME "UndrawResistor"
Toggle resistance undrawing.
.br
Only useful with resistance extraction enabled.
.ME "DrawOutResistor"
Toggle drawing of resistances that are written to database.
.br
Only useful with resistance extraction enabled.
.ME "DrawFEMesh"
Toggle finite-element drawing for resistance extraction.
.br
Only useful with resistance extraction enabled.
.ME "DrawEquiLines"
Toggle drawing of equi-potential lines in finite-element mesh.
.br
Only useful with resistance extraction enabled.
.ME "DrawCapacitor"
Toggle capacitance drawing.
.br
Only useful with capacitance extraction enabled.
.ME "UndrawCapacitor"
Toggle capacitance undrawing.
.br
Only useful with capacitance extraction enabled.
.ME "DrawOutCapacitor"
Toggle drawing of capacitances that are written to database.
.br
Only useful with capacitance extraction enabled.
.ME "DrawBEMesh"
Toggle drawing of the boundary-element mesh.
Only useful with 3D capacitance / substrate resistance extraction enabled.
.ME "DrawGreen"
Toggle drawing of the Green's function evaluations.
.br
Only useful in combination with \fBDrawBEMesh\fP.
.ME "3 dimensional"
Toggle 3D drawing for \fBDrawBEMesh\fP and \fBDrawGreen\fP.
.ME "DrawSubTerm"
Toggle 2D drawing of the edges of substrate terminals.
Only useful with substrate resistance extraction enabled.
.ME "FillSubTerm"
Toggle 2D drawing of the tiles of substrate terminals.
.ME "DrawDelaunay"
Toggle drawing of Delaunay diagram between substrate terminals.
Only useful with interpolated substrate resistance extraction enabled.
.ME "DrawSubResistor"
Toggle drawing of substrate resistances between substrate terminals
(only useful when sub. res. extraction is enabled).
'       \" .ME "dim"
'       \" Dim the colors.
.M)

.H 2 "Speed Scrollbar"
Click in the scrollbar window to choice another drawing speed
or drag the slider to another position.
To the left is slower (more delay) and to the right is faster.
You can also use the 'Page Down' and 'Page Up' hotkeys to set another speed.
With the above handlings you enter also the delayed extraction mode again (except in pause).
You can also use the \fBd\fP-key to go to the delayed mode.
.H 1 "Hotkeys"
You can use the keys of the keyboard to give commands to the
.P= Xspace
program.
Some of these commands are also menu buttons.
Most commands may also be given during the extraction process.
The not earlier mentioned keys are given below.
.H 2 "Camera Hotkeys"
See also the "Camera Parameters" section.
With the arrow hotkeys its is possible to change the camera viewpoint.
To see the new 3D drawing result, a new extraction must be done.
New values can only be chosen, when in "3 dimensional" mode.
.VL 20n 0.4c
.ME "KP Key: \(<-"
Camera longitude \(mi15 degrees.
.ME "KP Key: \(->"
Camera longitude +15 degrees.
.ME "KP Key: \(da"
Camera latitude \(mi15 degrees (minimum: 0 degrees).
.ME "KP Key: \(ua"
Camera latitude +15 degrees (maximum: 90 degrees).
.ME "KP Key: \(pl"
Increase the camera perspective distance.
.ME "KP Key: \(mi"
Decrease the camera perspective distance.
.ME "KP Key: \(**"
Toggle 3D drawing mode.
.M)
.H 2 "Coordinates Hotkeys"
A number of hotkeys is used to specify and display a coordinate point.
You can interactively enter a x,y,z-value.
The z-value is only used in 3D mode.
There are two interactive modi (the g-mode and z-mode).
The interactive modi are canceled, when you specify an incorrect hotkey.
.VL 20n 0.4c
.ME "Key: g"
Initiate to enter a goto point x-value (begin/change g-mode).
.ME "Key: ,"
Initiate to enter a goto point y-value (begin/change g-mode).
.br
In 3D mode, toggle between y-value and z-value.
.ME "Key: z"
Initiate to enter a goto point z-value (when in 3D g-mode).
.br
When not in g-mode, the current z-value can be changed
.br
(default 0) in the z-mode.
.ME "Key: Enter"
Display the entered goto point (end g-mode).
When the point is
.br
outside the window, jump to the coordinate point position.
You can directly give this command without entering the g-mode.
.ME "Keys: 0 \(mi 9"
To enter a digit for a coordinate value.
The first digit after
.br
an initiate clears the current value.
.ME "Key: ."
Enter a decimal point and maximum 3 digits behind it.
.br
Only valid when parameter "disp.coord_in_microns" is "on".
.ME "Key: \(mi"
To toggle the coordinate value from positive into negative.
.br
Note that a zero value can only be positive.
.ME "Key: ="
In g-mode, the x-value or y-value takes over the current value of the pointer position.
It initiate the x-value or y-value again.
.br
Outside g-mode, both the x-value and y-value are set.
.ME "Key: Backspace"
Delete the last digit (or decimal point) of a x,y,z-value.
.br
Note, also useful for adding digits to a value.
.ME "Key: Escape"
Cancel the current mode and display the cell bounding box.
.M)

.H 2 "Other Hotkeys"
.VL 20n 0.4c
.ME "Key: \(<-"
Move picture a half window to the left.
.ME "Key: \(->"
Move picture a half window to the right.
.ME "Key: \(da"
Move picture a half window down-wards.
.ME "Key: \(ua"
Move picture a half window up-wards.
.ME "Key: m"
Move picture on pointer position to middle of display.
.ME "Key: b"
Zoom in/out to the cell bounding box.
.ME "Key: i"
Zoom in on current pointer position.
.ME "Key: I"
Zoom in on middle of display.
.ME "Key: o"
Zoom out on current pointer position.
.ME "Key: O"
Zoom out on middle of display.
.ME "Key: u"
Undo last zoom.
.ME "Key: x"
Zoom, use position as new lower left corner.
.ME "Key: y"
Zoom, use position as new upper right corner.
.ME "Key: ."
Give layout position of current pointer position.
.ME "Key: Ctrl-c"
Abort extraction or extract again mode.
.ME "Key: Ctrl-l"
Redraw display, but do not use clear.
.M)
.H 1 "The Parameter File"
Besides that menu entries can be set by setting corresponding
commandline options (e.g. 
the menu entry "coupling cap."
can also be set by setting the commandline option
.O= -C -coupcap "" ),
entries from the menu can also be set by setting corresponding
parameters in the space parameter file.
Setting the following \fIboolean\fP parameters corresponds to setting
the following menu entries:
.DS I
.TS
l l.
parameter	menu entry
_
disp.sync	sync
disp.be_mesh_only	BE mesh only
disp.pair_boundary	PairBoundary
disp.draw_tile	DrawTile
disp.draw_edge	DrawEdge
disp.draw_resistor	DrawResistor
disp.undraw_resistor	UndrawResistor
disp.draw_out_resistor	DrawOutResistor
disp.draw_capacitor	DrawCapacitor
disp.undraw_capacitor	UndrawCapacitor
disp.draw_out_capacitor	DrawOutCapacitor
disp.draw_fe_mesh	DrawFEMesh
disp.draw_equi_lines	DrawEquiLines
disp.draw_be_mesh	DrawBEMesh
disp.draw_green	DrawGreen
disp.3_dimensional	3 dimensional
disp.draw_sub_term	DrawSubTerm
disp.draw_delaunay	DrawDelaunay
disp.draw_sub_resistor	DrawSubResistor
.TE
'       \" disp.dim	dim
.DE
The following two integer parameters may be used to set
the width and height of the display window.
.DS I
.TS
l l.
disp.width	\fIwidth\fP    
disp.height	\fIheight\fP
.TE
.DE
With the following parameter the window of the layout that is
displayed is specified (default the whole layout is displayed).
The parameter requires as arguments the x-left, x-right, y-bottom and
y-top coordinates of the window.
The coordinates are specified in database units (lambda).
.DS I
.TS
l l.
disp.layout_window	\fIxl  xr  yb  yt\fP    
.TE
.DE
When the following parameter is "on",
substrate terminals are drawn with their tile (mask) color.
When it is "off", only the border of the substrate terminals is drawn.
.DS I
.TS
l l.
disp.fill_sub_term	\fIboolean\fP    (default: "on")    
.TE
.DE
When the following parameter is "on",
drawing results of extraction prepasses are not cleared.
This makes it possible to e.g. keep the boundary-element mesh
of substrate resistance extraction in the final picture that is displayed.
.DS I
.TS
l l.
disp.save_prepass_image	\fIboolean\fP    (default: "off")
.TE
.DE
Set the following parameter, when no display clear must be done before a new extraction.
It keeps the current window contents and dimension.
.DS I
.TS
l l.
disp.save_extract_image	\fIboolean\fP    (default: "off")
.TE
.DE
When the following parameter is set to "off",
the menu bar of
.P= Xspace
is omitted.
The default value is "on" for
.P= Xspace
and "off" for
.P= space3d
using the \fB-X\fP option.
.DS I
.TS
l l.
disp.show_menu	\fIboolean\fP
.TE
.DE
.H 2 "Camera Parameters"
The point of view for a 3D picture can be changed with the following two parameters.
With the camera latitude parameter set to 90 degrees you are looking from above to
the picture.
.DS I
.TS
l l.
disp.cam_latitude	\fIreal\fP    (default: 30 degrees)
.TE
.DE
With the following parameter you can set the camera longitude.
With the default you see the x-axis from left to right.
.DS I
.TS
l l.
disp.cam_longitude	\fIreal\fP    (default: 270 degrees)
.TE
.DE
With the following parameter you can set the camera distance,
to get more or less perspective.
.DS I
.TS
l l.
disp.cam_distance	\fIreal\fP    (default: 2.0)
.TE
.DE
With the following parameter you can set parallel perspective.
.DS I
.TS
l l.
disp.cam_parallel	\fIboolean\fP    (default: "off")
.TE
.DE
.H 2 "Other Parameters"
With the following parameter you can specify an alternate substrate contact fill color
(used for 2D tile drawing).
This new color is only used in place of "black" color fills.
Note that both "Display Menu" settings "DrawTile" and "DrawSubTerm" must be "on".
.DS I
.TS
l l.
disp.def_color_sub_con	\fIstring\fP   (default: "white")
.TE
.DE
.P= Xspace
tries to use the GXor mode for the graphics context.
However, when the picture looks incorrect, you can set the GXcopy mode.
.DS I
.TS
l l.
disp.use_pixel_copy_mode	\fIboolean\fP   (default: "off")
.TE
.DE
To set another file for the "robot" menu command, give
the following parameter:
.DS I
.TS
l l.
disp.program_file	\fIstring\fP    (default: "program")
.TE
.DE
Additional drawing commands may be given from a drawing file.
When you want this, specify with the following parameter the name of this file:
.DS I
.TS
l l.
disp.draw_file	\fIstring\fP    (default: none)
.TE
.DE
The displayed coordinates (see '.', 'g' and 'z' keys) are default in internal units.
To use database units or microns, specify one of the following parameters:
.DS I
.TS
l l.
disp.coord_in_dbunits	\fIboolean\fP    (default: "off")
disp.coord_in_microns	\fIboolean\fP    (default: "off")
.TE
.DE

.H 2 "Draw File Commands"
Each line of the "draw_file" can contain a drawing command.
To execute the command, it must begin at the first position on the line.
The most simple command draws a dot on the screen.
To do this, you need only to specify a x-value and y-value.
Blanks may be used (no tabs) to separate the values.
A comma directly behind the value may also be used.
A comma behind a y-value is needed to specify a z-value for 3D mode.
When no z-value is given, zero is used.
The second coordinate point inherit default the z-value of the first point.
The x-value and y-value must always be specified.
Note that all other commands begin with a command key letter.
All commands (except the unit commands) may be followed by a text string, which must be displayed.
All coordinate values are default in internal units.
.sp
The following unit and drawing commands can be used:
.DS I
.TS
l l.
\fBd\fP	use database units for coordinate values
\fBi\fP	use internal units for coordinate values
\fBm\fP	use microns for coordinate values
\fBx\fP x,y	draw a small cross at given position
\fBX\fP x,y	draw a bigger cross at given position
\fBp\fP x,y	draw a small plus at given position
\fBP\fP x,y	draw a bigger plus at given position
\fBh\fP x,y	draw a small hor.mark at given position
\fBH\fP x,y	draw a bigger hor.mark at given position
\fBv\fP x,y	draw a small vert.mark at given position
\fBV\fP x,y	draw a bigger vert.mark at given position
\fBl\fP p1 p2	draw a line between the two given points
\fBr\fP p1 p2	draw a rectangle using the two given points
\fBy\fP p1 p2	draw 3D rectangle around y-axis using the two points
\fBz\fP p1 p2	draw 3D rectangle around z-axis using the two points
.TE
.DE
.H 1 "Mask Colors"
The colors that are used to display the different masks/conductors,
are specified in the space element definition technology file.
The specification must be placed after
the (optional) specification of the new masks.
.P
Syntax:
.DS I
\fCcolors\fP :
   \fImask color\fP
     ...
.DE
A specification consists of a mask name followed by a color.
The mask name may be an original mask name, a mask name created using
the "new" statement, or the string "@sub".
For masks that are created in the element definition file 
using the "new" statement and for the "@sub" mask,
only boundary-elements of conductors of that mask will be drawn in that color
(i.e. DrawTile will \fBnot\fP draw the color of that mask).
.P
Available color names are all X\ color names
(these are normally found in the file '/usr/lib/X11/rgb.txt'),
including the special color 'glass' which means in fact 'invisible'.
Moreover, RGB values can be specified in the X\ fashion with the '#'
character replaced by the '@' character, since the former is already
used to specify comment in the element definition file.
Black is drawn dominant, all other colors are mixed.  For example,
red and green becomes yellow.
.P
Note, define only colors for masks when needed.
Each new color (except white & black) doubles the internal colormap space.
Note that a maximum of 20 different colors can be used for transparent
tile drawing.
.P
An example to specify the colors of masks np, nd, nm, ni, ...
and @sub is as follows:
.fS I
colors :
    np     red
    nd     green
    nm     blue
    ni     @CCC
    nb     magenta
    nx     cyan
    ng     black
    nc     black
    @sub   pink
.fE
The user can overwrite one of the above color specifications by specifying
a "color_\fImaskname\fP" parameter in the space parameter file.
For example:
.fS I
disp.color_ni    @C8F
disp.color_@sub  orange
.fE
.H 1 "Usage of .Xdefaults"
The \fI.Xdefaults\fP file in the users home directory is used to set
X Windows related preferences (unless a resource database was build
using the command 'xrdb').
Since 
.P= Xspace 
uses the X toolkit and the resource manager
a very large number of parameters can be changed by the user.
The following is a list of some of the more useful resources with their
default values:
.L{
.TS
tab(@);
a a.
Xspace*.background:@LightSteelBlue
Xspace*.borderColor:@black
Xspace*.font:@screen.b.16
Xspace*Command.background:@yellow
Xspace*Command.foreground:@black
Xspace*Label.background:@yellow
Xspace*Label.foreground:@black
Xspace*Scrollbar.background:@yellow
Xspace*Scrollbar.foreground:@black
Xspace*canvas.borderColor:@LightSteelBlue
Xspace*canvas.borderWidth:@5
Xspace*canvas.height:@375
Xspace*canvas.width:@500
Xspace*delayWidget:@True
Xspace*menu.borderColor:@LightSteelBlue
Xspace*menu.hSpace:@2
Xspace*menu.vSpace:@10
Xspace*menuAside:@False
Xspace*messageWindow:@False
.TE
.L}
