
/*
 * ISC License
 *
 * Copyright (C) 1987-2015 by
 *	Arjan van Genderen
 *	Peter Elias
 *	Sander de Graaf
 *	Simon de Graaf
 *	Nick van der Meijs
 * Delft University of Technology
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

#include <time.h>
#include "src/xvhdl/incl.h"

#define TOOLVERSION "3.03 10-Aug-2015"

char *argv0 = "xvhdl";
char *use_msg = "\nUsage: %s [-fhirv -w width -C file -D name -F outfile -X lib] cell\n\n";

DM_PROJECT *dmproject = NULL;

FILE *fp_out;
long *Nil = NULL;
int maxLL = 92; /* maximum output line length */
int tog_prExt = 1;
int xtree = 0;
int alsoImport = 0;
int verbose = 0;
int ofile = 0;
char *outFile = NULL;
char ofname[BUFSIZ];

char *controlFile = NULL;
char *controlLabel = NULL;

struct node_ref *Node_list = NULL;
struct node_ref *Node_list_free = NULL;
struct node_ref *Node_list_last;

struct lib_model *lm_head = NULL;

char *excl_lib[40];
int excl_lib_cnt = 0;

char *xvhdl_net_prefix;

static void initIntrup (void);

static void writeHeader ()
{
    struct tm *tstruct;
    time_t tval;
    char buf[BUFSIZ];
    char *mon = "???";
    char *fn = ".sls2vhdl";
    FILE *fp;
    int year;

    time (&tval);
    tstruct = localtime (&tval);
    year = tstruct -> tm_year + 1900;

    switch (tstruct -> tm_mon) {
	case  0: mon = "Jan"; break;
	case  1: mon = "Feb"; break;
	case  2: mon = "Mar"; break;
	case  3: mon = "Apr"; break;
	case  4: mon = "May"; break;
	case  5: mon = "Jun"; break;
	case  6: mon = "Jul"; break;
	case  7: mon = "Aug"; break;
	case  8: mon = "Sep"; break;
	case  9: mon = "Oct"; break;
	case 10: mon = "Nov"; break;
	case 11: mon = "Dec"; break;
    }

    fprintf (fp_out, "-- Generated by: %s %s\n", argv0, TOOLVERSION);
    fprintf (fp_out, "-- Date: %d-%s-%d %d:%02d:%02d\n",
	tstruct -> tm_mday, mon, year,
	tstruct -> tm_hour, tstruct -> tm_min,  tstruct -> tm_sec);
    fprintf (fp_out, "-- Path: %s\n", dmproject -> dmpath);
    fprintf (fp_out, "\nLIBRARY IEEE; USE IEEE.STD_LOGIC_1164.ALL;\n");
    fprintf (fp_out, "\n-- user directives added from %s\n", fn);

    if ((fp = fopen (fn, "r"))) {
	while (fgets (buf, BUFSIZ, fp)) fputs (buf, fp_out);
	fclose (fp);
    }
}

int main (int argc, char *argv[])
{
    char *s, *t;
    char *network;
    struct cir *cl;

    network = NULL;

    if ((s = strrchr (*argv, '/'))) ++s;
    else if ((s = strrchr (*argv, '\\'))) ++s;
    else s = *argv;
#ifdef WIN32
    if ((t = strchr (s, '.'))) *t = 0;
#endif

    if (argc <= 1) P_E "%s %s\n", argv0, TOOLVERSION);

    while (--argc > 0) {
	if ((*++argv)[0] == '-') {
	    for (s = *argv + 1; *s; s++) {
		switch (*s) {
		    case 'C':
			controlFile = *++argv;
			if (*(s + 1) || --argc <= 0 || !*controlFile) {
			    P_E use_msg, argv0);
			    exit (1);
			}
			break;
		    case 'w':
		    case 'D':
			t = *++argv;
			if (*(s + 1) || --argc <= 0 || !*t) {
			    P_E use_msg, argv0);
			    exit (1);
			}
			if (*s == 'w') {
			    maxLL = atoi (t);
			    if (maxLL && maxLL < 40) maxLL = 40;
			    break;
			}
			controlLabel = t;
			while (*t) { *t = toupper (*t); ++t; }
			break;
		    case 'f':
			ofile = 1;
			break;
		    case 'F':
			ofile = 1;
			outFile = *++argv;
			if (*(s + 1) || --argc <= 0 || !*outFile) {
			    P_E use_msg, argv0);
			    exit (1);
			}
			break;
		    case 'h':
			xtree = 1;
			break;
		    case 'i':
			alsoImport = 1;
			break;
		    case 'X':
			t = *++argv;
			if (*(s + 1) || --argc <= 0 || !*t) {
			    P_E use_msg, argv0);
			    exit (1);
			}
			if (excl_lib_cnt < 40)
			    excl_lib[excl_lib_cnt++] = strsave (t);
			break;
		    case 'v':
			verbose = 1;
			break;
		    case 'r': tog_prExt = 0; break;
		    default:
			P_E "%s: illegal option: %c\n", argv0, *s);
			exit (1);
		}
	    }
	}
	else {
	    if (!network) network = *argv;
	    else {
		P_E use_msg, argv0);
		exit (1);
	    }
	}
    }
    if (!network) {
	P_E use_msg, argv0);
	exit (1);
    }

    dmInit (argv0);
    dmproject = dmOpenProject (DEFAULT_PROJECT, DEFAULT_MODE);

    dm_get_do_not_alloc = 1; /* fast circuit streams read */

    initIntrup ();

    if (ofile) {
        if (outFile) sprintf (ofname, outFile);
        else sprintf (ofname, "%s.vhd", network);
	OPENW (fp_out, ofname);
    }
    else fp_out = stdout;

    if (!(xvhdl_net_prefix = getenv ("XVHDL_NET_PREFIX"))) xvhdl_net_prefix = "N_";

    initDevs ();

    readControl ();

    writeHeader ();

    for (cl = cirTree (network); cl; cl = cl -> next) {
	if (verbose) P_E "Extracting %s\n", cl -> name);
	xnetwork (cl);
    }

    oprint (0, "\n"); /* to empty the buffer */

    if (ofile) CLOSE (fp_out);

    if (dmproject) dmCloseProject (dmproject, COMPLETE);
    dmQuit ();

    return (0);
}

int isCurrentDialect (char *buf)
{
    char *s = buf;
    while (*s) { *s = toupper (*s); ++s; }

    if (controlLabel && strcmp (buf, controlLabel) == 0) return (1);

    return (strcmp (buf, "VHDL") == 0);
}

void fatalErr (char *s1, char *s2)
{
    P_E "%s:", argv0);
    if (s1 && *s1) P_E " %s", s1);
    if (s2 && *s2) P_E " %s", s2);
    P_E "\n");
    if (ofile && fp_out) {
	oprint (0, ""); /* to empty the buffer */
	fprintf (fp_out, "\nfatalError:");
	if (s1 && *s1) fprintf (fp_out, " %s", s1);
	if (s2 && *s2) fprintf (fp_out, " %s", s2);
	fprintf (fp_out, "\n");
    }
    die ();
}

void int_hdl (int sig) /* interrupt handler */
{
    char *s;
    switch (sig) {
#ifdef SIGILL
	case SIGILL: s = "Illegal instruction"; break;
#endif
#ifdef SIGFPE
	case SIGFPE: s = "Floating point exception"; break;
#endif
#ifdef SIGBUS
	case SIGBUS: s = "Bus error"; break;
#endif
#ifdef SIGSEGV
	case SIGSEGV: s = "Segmentation violation"; break;
#endif
	default: s = "Unknown signal"; break;
    }
    P_E "%s\n", s);
    if (ofile && fp_out) {
	oprint (0, ""); /* to empty the buffer */
	fprintf (fp_out, "\ninterruptError: Some signal occurred!\n");
    }
    die ();
}

static void initIntrup ()
{
#define install_handler(sig) signal (sig, int_hdl)
#ifdef SIGINT
    if (signal (SIGINT, SIG_IGN) != SIG_IGN) install_handler (SIGINT);
#endif
#ifdef SIGQUIT
    if (signal (SIGQUIT, SIG_IGN) != SIG_IGN) install_handler (SIGQUIT);
#endif
#ifdef SIGTERM
    install_handler (SIGTERM);
#endif
#ifdef SIGILL
    install_handler (SIGILL);
#endif
#ifdef SIGFPE
    install_handler (SIGFPE);
#endif
#ifdef SIGBUS
    install_handler (SIGBUS);
#endif
#ifdef SIGSEGV
    install_handler (SIGSEGV);
#endif
}

void dmError (char *s)
{
    P_E "%s: ", argv0);
    dmPerror (s);
    if (ofile && fp_out) {
	oprint (0, ""); /* to empty the buffer */
	fprintf (fp_out, "\ndmError: %s: Error in database function!\n", s);
    }
    die ();
}

void die ()
{
    if (ofile && fp_out) { CLOSE (fp_out); fp_out = NULL; }
    dmQuit ();
    exit (1);
}

void cannot_die (int nr, char *fn)
{
    char *s;

    switch (nr) {
	case 1: s = "Cannot allocate"; fn = "storage"; break;
	case 2: s = "Cannot read file:"; break;
	case 3: s = "Cannot write file:"; break;
	default:
	case 4: s = "Internal error:"; break;
    }
    P_E "%s: %s %s\n", argv0, s, fn);
    if (ofile && fp_out) {
	oprint (0, ""); /* to empty the buffer */
	fprintf (fp_out, "\nError: %s %s!\n", s, fn);
    }
    die ();
}
